version: '3'

services:
  apigateway:
    image: nginx:alpine
    ports:
      - 3000:80
    volumes:
      - ./tools/nginx/nginx.conf:/etc/nginx/nginx.conf

  device:
    build: .
    environment:
    - APP_NAME=device
    - DB_DSN=postgresql://deviceservice:deviceservice@db:5432/deviceservice?sslmode=disable
    volumes:
      - ./:/workspace:cached

  pipeline:
    build: .
    environment:
    - APP_NAME=pipeline
    - DB_DSN=postgresql://pipelineservice:pipelineservice@db:5432/pipelineservice?sslmode=disable
    - HTTP_ADDR=:3000
    volumes:
      - ./:/workspace:cached

  httpimporter:
    build: .
    volumes:
      - .:/workspace:cached
    environment:
    - APP_NAME=httpimporter
    - HTTP_ADDR=:3000
    - AMQP_HOST=amqp://guest:guest@mq:5672/
    - AMQP_XCHG=pipeline.messages
    - SVC_PIPELINE=http://pipeline:3000

  measurements:
    build: .
    volumes:
      - .:/workspace:cached
    environment:
    - APP_NAME=measurements
    - HTTP_BASE=http://localhost:3000/measurements
    - HTTP_ADDR=:3000
    - DB_DSN=postgresql://measurementservice:measurementservice@db:5432/measurementservice?sslmode=disable
    - AMQP_HOST=amqp://guest:guest@mq:5672/
    - AMQP_XCHG=pipeline.measurement.tx
    - AMQP_QUEUE=measurement_service_q

  worker_thethingsnetwork:
    build: .
    volumes:
      - .:/workspace:cached
    environment:
    - APP_NAME=the-things-network
    - APP_TYPE=worker
    - AMQP_HOST=amqp://guest:guest@mq:5672/
    - AMQP_QUEUE=the-things-network
    - AMQP_XCHG=pipeline.messages
    - SVC_DEVICE=http://device:3000

  worker_multiflexmeter:
    build: .
    volumes:
      - .:/workspace:cached
    environment:
    - APP_NAME=multiflexmeter-groundwater-level
    - APP_TYPE=worker
    - AMQP_HOST=amqp://guest:guest@mq:5672/
    - AMQP_QUEUE=multiflexmeter-groundwater-level
    - AMQP_XCHG=pipeline.messages

  db:
    image: timescale/timescaledb-postgis:latest-pg12
    ports:
      - 5432:5432
    volumes:
      - ./tools/postgres.d:/docker-entrypoint-initdb.d
    environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=sensorbucket
    - POSTGRES_DB=sensorbucket
  dbweb:
    image: michalhosna/adminer
    environment:
        ADMINER_DRIVER: pgsql
        ADMINER_SERVER: db
        ADMINER_DB: sensorbucket
        ADMINER_USERNAME: user
        ADMINER_PASSWORD: sensorbucket
        ADMINER_AUTOLOGIN: 1

  mq:
    image: rabbitmq:3.8-management
    ports:
      - 15672:15672

  openapi:
    image: swaggerapi/swagger-editor
    environment:
      - URL=/openapi/ref/api.yaml
      - BASE_URL=/openapi
    volumes:
      - ./tools/openapi/ref:/usr/share/nginx/html/ref

networks:
  default:
    name: sensorbucket_network
