site_name: Sensorbucket
repo_url: https://gitlab.com/sensorbucket
repo_name: Sensorbucket
theme:
  name: material
  logo: sensorbucket-logo-white.png
  favicon: sensorbucket-logo.png
  icon:
    repo: fontawesome/brands/git-alt 
  palette:
    - scheme: slate
      primary: teal
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  features:
    - navigation.sections

plugins:
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Overview: index.md
  - Introduction: introduction.md
  - Development:
    - Architecture: development/architecture.md
    - Data Model: development/data-model.md
  - API Reference: ./api/index.html
