site_name: SensorBucket
repo_url: https://github.com/sensorbucket/sensorbucket
repo_name: SensorBucket
theme:
  name: material
  logo: sensorbucket-logo-white.png
  favicon: sensorbucket-logo.png
  icon:
    repo: fontawesome/brands/git-alt 
  palette:
    - scheme: slate
      primary: teal
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  features:
    - navigation.sections

plugins:
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Overview: index.md
  - Introduction: introduction.md
  - Supporting new devices: creating-workers.md
  - Importing resources from a CSV: importer.md
  - Development:
    - Architecture: development/architecture.md
    - Data Model: development/data-model.md
    - Workers and Fission: development/user-workers.md
    - Services:
      - Core: development/core.md
      - Dashboard: development/dashboard.md
      - HTTP Ingress: development/http-importer.md
      - Tracing: development/tracing.md
      - Fission User Workers: development/fission-user-workers.md
      - Fission RMQ Connector: development/fission-rmq-connector.md
      - Workers: development/workers.md
  - API Reference: ./api/index.html
