site_name: Sensorbucket
repo_url: https://gitlab.com/sensorbucket
repo_name: Sensorbucket
theme:
  name: material
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/git-alt 
  palette:
    - scheme: slate
      primary: deep orange
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      primary: deep orange
      accent: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home:
    - Introduction: index.md
    - Getting started: getting-started.md
  - Services:
    - Asset Manager: assetmanager/index.md
    - Measurements: measurements/index.md
