BEGIN;
ALTER TABLE measurements ADD COLUMN created_at TIMESTAMPTZ DEFAULT(NOW() AT TIME ZONE 'UTC') NOT NULL;
ALTER TABLE datastreams ADD COLUMN created_at TIMESTAMPTZ DEFAULT(NOW() AT TIME ZONE 'UTC') NOT NULL;
COMMIT;
