openapi: 3.0.0
info:
  title: Sensorbucket API
  version: '1.0'
  license:
    name: TBD
  description: ''
  contact:
    name: Provincie Zeeland
    url: 'https://zeeland.nl'
servers:
  - description: Local
    url: 'http://localhost:3000'
paths: 
  /hello-world:
    get:
      description: Hello world!
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: "Hello world!"
  
  /assets:
    post:
      description: Create an asset
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [type, body]
              properties:
                type:
                  type: string
                  example: sensor
                body:
                  type: object
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/assetResponse"
    get:
      parameters:
        - in: query
          name: type
          schema:
            type: string
        - in: query
          name: filter
          schema:
            type: array
            items:
              type: string
      description: List and filter assets
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/assetResponse"

  
  /assets/{assetURN}:
    parameters:
      - name: assetURN
        in: path
        required: true
        schema:
          type: string
    get:
      description: Retrieve an asset
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/assetResponse"

components:
  schemas: 
    assetResponse:
      type: object
      properties:
        urn:
          type: string
          example: "sb:pipelineasset:mfm-waterlevel:sensor:12345678"
        content:
          type: object
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
security:
  - Authorization: []
tags: []
