openapi: 3.0.0
info:
  title: Sensorbucket API
  version: '1.0'
  license:
    name: TBD
  description: ''
  contact:
    name: Provincie Zeeland
    url: 'https://zeeland.nl'
servers:
  - description: Asset Manager
    url: 'http://localhost:3000'
  - description: Measurements
    url: 'http://localhost:3001'
paths: 
  /hello-world:
    get:
      description: Hello world!
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: "Hello world!"
  
  /asset-definitions:
    get:
      description: List asset definitions for this AM service
      tags: ["Asset Management"]
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /assets:
    post:
      description: Create an asset
      tags: ["Asset Management"]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [asset_definition, content]
              properties:
                asset_definition:
                  type: string
                  example: srn:asset:mfm-waterlevel:sensor
                content:
                  type: object
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/assetResponse"
    get:
      parameters:
        - in: query
          name: assetDefinition
          schema:
            type: string
        - in: query
          name: filter
          schema:
            type: array
            items:
              type: string
      description: List and filter assets
      tags: ["Asset Management"]
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/assetResponse"

  
  /assets/{assetURN}:
    parameters:
      - name: assetURN
        in: path
        required: true
        schema:
          type: string
    get:
      description: Retrieve an asset
      tags: ["Asset Management"]
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/assetResponse"
    put:
      description: Replace an asset definition
      tags: ["Asset Management"]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [content]
              properties:
                content:
                  type: object
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/assetResponse"

  /{start}/{end}:
    parameters:
      - in: path
        name: start
        required: true
        schema:
          type: string
          format: iso8601
      - in: path
        name: end
        required: true
        schema:
          type: string
          format: iso8601
    get:
      description: query measurements
      tags: ["Measurements"]
      parameters:
        - in: query
          name: thing_urn
          required: false
          schema:
            type: string
            example: "srn:asset:mfm-waterlevel:sensor:12345678"
        - in: query
          name: location_id
          required: false
          schema:
            type: number
            example: 12
        - in: query
          name: measurement_type
          required: false
          schema:
            type: string
            example: "air_temperature"
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/measurementResponse"
        

components:
  schemas: 
    assetResponse:
      type: object
      properties:
        urn:
          type: string
          example: "srn:asset:mfm-waterlevel:sensor:12345678"
        content:
          type: object
    measurementResponse:
      type: object
      properties:
        thing_urn:
          type: string
          example: "srn:asset:mfm-waterlevel:sensor:12345678"
        timestamp:
          type: string
          example: "2022-02-01T12:14:00+02:00"
        value:
          type: number
          example: 21.325
        measurement_type:
          type: string
          example: air_temperature
        measurement_type_unit:
          type: string
          example: degrees celsius
        location_id:
          type: number
          example: 12
        coordinates:
          type: array
          items: 
            type: number
          example: [5.47, 51.46]
        metadata:
          type: object
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
security:
  - Authorization: []
tags:
  - name: Asset Management
