openapi: 3.0.0
info:
  title: Sensorbucket API
  version: '1.0'
  license:
    name: TBD
  description: ''
  contact:
    name: Provincie Zeeland
    url: 'https://zeeland.nl'
servers:
  - description: Local
    url: 'http://localhost:3000'
paths: 
  /hello-world:
    get:
      description: Hello world!
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: "Hello world!"
  
  /assets/{assetType}:
    parameters:
      - name: assetType
        in: path
        required: true
        schema:
          type: string
    post:
      description: Create an asset
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
  
  /assets/{assetType}/{assetID}:
    parameters:
      - name: assetType
        in: path
        required: true
        schema:
          type: string
      - name: assetID
        in: path
        required: true
        schema:
          type: string
    get:
      description: Retrieve an asset
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: object

components:
  schemas: {}
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
security:
  - Authorization: []
tags: []
