/*
Sensorbucket API

SensorBucket processes data from different sources and devices into a single standardized format.  An applications connected to SensorBucket, can use all devices SensorBucket supports.  Missing a device or source? SensorBucket is designed to be scalable and extendable. Create your own worker that receives data from an AMQP source, process said data and output in the expected worker output format.  Find out more at: https://developer.sensorbucket.nl/  Developed and designed by Provincie Zeeland and Pollex 

API version: 1.0
Contact: info@pollex.nl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the UpdateSensorGroupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSensorGroupRequest{}

// UpdateSensorGroupRequest struct for UpdateSensorGroupRequest
type UpdateSensorGroupRequest struct {
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

// NewUpdateSensorGroupRequest instantiates a new UpdateSensorGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSensorGroupRequest() *UpdateSensorGroupRequest {
	this := UpdateSensorGroupRequest{}
	return &this
}

// NewUpdateSensorGroupRequestWithDefaults instantiates a new UpdateSensorGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSensorGroupRequestWithDefaults() *UpdateSensorGroupRequest {
	this := UpdateSensorGroupRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateSensorGroupRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSensorGroupRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateSensorGroupRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateSensorGroupRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateSensorGroupRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSensorGroupRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateSensorGroupRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateSensorGroupRequest) SetDescription(v string) {
	o.Description = &v
}

func (o UpdateSensorGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSensorGroupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableUpdateSensorGroupRequest struct {
	value *UpdateSensorGroupRequest
	isSet bool
}

func (v NullableUpdateSensorGroupRequest) Get() *UpdateSensorGroupRequest {
	return v.value
}

func (v *NullableUpdateSensorGroupRequest) Set(val *UpdateSensorGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSensorGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSensorGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSensorGroupRequest(val *UpdateSensorGroupRequest) *NullableUpdateSensorGroupRequest {
	return &NullableUpdateSensorGroupRequest{value: val, isSet: true}
}

func (v NullableUpdateSensorGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSensorGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


