/*
Sensorbucket API

SensorBucket processes data from different sources and devices into a single standardized format.  An applications connected to SensorBucket, can use all devices SensorBucket supports.  Missing a device or source? SensorBucket is designed to be scalable and extendable. Create your own worker that receives data from an AMQP source, process said data and output in the expected worker output format.  Find out more at: https://developer.sensorbucket.nl/  Developed and designed by Provincie Zeeland and Pollex 

API version: 1.0
Contact: info@pollex.nl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// CreateSensorGroup201Response struct for CreateSensorGroup201Response
type CreateSensorGroup201Response struct {
	Message *string `json:"message,omitempty"`
	Data *SensorGroup `json:"data,omitempty"`
}

// NewCreateSensorGroup201Response instantiates a new CreateSensorGroup201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSensorGroup201Response() *CreateSensorGroup201Response {
	this := CreateSensorGroup201Response{}
	return &this
}

// NewCreateSensorGroup201ResponseWithDefaults instantiates a new CreateSensorGroup201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSensorGroup201ResponseWithDefaults() *CreateSensorGroup201Response {
	this := CreateSensorGroup201Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateSensorGroup201Response) GetMessage() string {
	if o == nil || isNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSensorGroup201Response) GetMessageOk() (*string, bool) {
	if o == nil || isNil(o.Message) {
    return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateSensorGroup201Response) HasMessage() bool {
	if o != nil && !isNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreateSensorGroup201Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateSensorGroup201Response) GetData() SensorGroup {
	if o == nil || isNil(o.Data) {
		var ret SensorGroup
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSensorGroup201Response) GetDataOk() (*SensorGroup, bool) {
	if o == nil || isNil(o.Data) {
    return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateSensorGroup201Response) HasData() bool {
	if o != nil && !isNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given SensorGroup and assigns it to the Data field.
func (o *CreateSensorGroup201Response) SetData(v SensorGroup) {
	o.Data = &v
}

func (o CreateSensorGroup201Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !isNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableCreateSensorGroup201Response struct {
	value *CreateSensorGroup201Response
	isSet bool
}

func (v NullableCreateSensorGroup201Response) Get() *CreateSensorGroup201Response {
	return v.value
}

func (v *NullableCreateSensorGroup201Response) Set(val *CreateSensorGroup201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSensorGroup201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSensorGroup201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSensorGroup201Response(val *CreateSensorGroup201Response) *NullableCreateSensorGroup201Response {
	return &NullableCreateSensorGroup201Response{value: val, isSet: true}
}

func (v NullableCreateSensorGroup201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSensorGroup201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


