/*
Sensorbucket API

SensorBucket processes data from different sources and devices into a single standardized format.  An applications connected to SensorBucket, can use all devices SensorBucket supports.  Missing a device or source? SensorBucket is designed to be scalable and extendable. Create your own worker that receives data from an AMQP source, process said data and output in the expected worker output format.  Find out more at: https://developer.sensorbucket.nl/  Developed and designed by Provincie Zeeland and Pollex 

API version: 1.0
Contact: info@pollex.nl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the GetDatastream200ResponseDataAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDatastream200ResponseDataAllOf{}

// GetDatastream200ResponseDataAllOf struct for GetDatastream200ResponseDataAllOf
type GetDatastream200ResponseDataAllOf struct {
	Device *Device `json:"device,omitempty"`
	Sensor *Sensor `json:"sensor,omitempty"`
}

// NewGetDatastream200ResponseDataAllOf instantiates a new GetDatastream200ResponseDataAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDatastream200ResponseDataAllOf() *GetDatastream200ResponseDataAllOf {
	this := GetDatastream200ResponseDataAllOf{}
	return &this
}

// NewGetDatastream200ResponseDataAllOfWithDefaults instantiates a new GetDatastream200ResponseDataAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDatastream200ResponseDataAllOfWithDefaults() *GetDatastream200ResponseDataAllOf {
	this := GetDatastream200ResponseDataAllOf{}
	return &this
}

// GetDevice returns the Device field value if set, zero value otherwise.
func (o *GetDatastream200ResponseDataAllOf) GetDevice() Device {
	if o == nil || IsNil(o.Device) {
		var ret Device
		return ret
	}
	return *o.Device
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDatastream200ResponseDataAllOf) GetDeviceOk() (*Device, bool) {
	if o == nil || IsNil(o.Device) {
		return nil, false
	}
	return o.Device, true
}

// HasDevice returns a boolean if a field has been set.
func (o *GetDatastream200ResponseDataAllOf) HasDevice() bool {
	if o != nil && !IsNil(o.Device) {
		return true
	}

	return false
}

// SetDevice gets a reference to the given Device and assigns it to the Device field.
func (o *GetDatastream200ResponseDataAllOf) SetDevice(v Device) {
	o.Device = &v
}

// GetSensor returns the Sensor field value if set, zero value otherwise.
func (o *GetDatastream200ResponseDataAllOf) GetSensor() Sensor {
	if o == nil || IsNil(o.Sensor) {
		var ret Sensor
		return ret
	}
	return *o.Sensor
}

// GetSensorOk returns a tuple with the Sensor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDatastream200ResponseDataAllOf) GetSensorOk() (*Sensor, bool) {
	if o == nil || IsNil(o.Sensor) {
		return nil, false
	}
	return o.Sensor, true
}

// HasSensor returns a boolean if a field has been set.
func (o *GetDatastream200ResponseDataAllOf) HasSensor() bool {
	if o != nil && !IsNil(o.Sensor) {
		return true
	}

	return false
}

// SetSensor gets a reference to the given Sensor and assigns it to the Sensor field.
func (o *GetDatastream200ResponseDataAllOf) SetSensor(v Sensor) {
	o.Sensor = &v
}

func (o GetDatastream200ResponseDataAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDatastream200ResponseDataAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Device) {
		toSerialize["device"] = o.Device
	}
	if !IsNil(o.Sensor) {
		toSerialize["sensor"] = o.Sensor
	}
	return toSerialize, nil
}

type NullableGetDatastream200ResponseDataAllOf struct {
	value *GetDatastream200ResponseDataAllOf
	isSet bool
}

func (v NullableGetDatastream200ResponseDataAllOf) Get() *GetDatastream200ResponseDataAllOf {
	return v.value
}

func (v *NullableGetDatastream200ResponseDataAllOf) Set(val *GetDatastream200ResponseDataAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDatastream200ResponseDataAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDatastream200ResponseDataAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDatastream200ResponseDataAllOf(val *GetDatastream200ResponseDataAllOf) *NullableGetDatastream200ResponseDataAllOf {
	return &NullableGetDatastream200ResponseDataAllOf{value: val, isSet: true}
}

func (v NullableGetDatastream200ResponseDataAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDatastream200ResponseDataAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


