version: v1.0.0 

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:3000/.ory
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:3000/tenants/auth/settings
  allowed_return_urls:
    - http://127.0.0.1:3000/tenants/auth/settings
    - http://127.0.0.1:3000/dashboard

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: SensorBucket
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true
    # Note: WebAuthn does not work in local environments since a domain name and HTTPS is required.
    # it might work using something like cloudflare tunnels, but requires a consistent domain name
    webauthn:
      enabled: true
      config:
        passwordless: false
        rp:
          id: mydomainname.com
          origins:
            - https://mydomainname.com
          display_name: SensorBucket

  flows:
    error:
      ui_url: http://127.0.0.1:3000/tenants/auth/error

    settings:
      ui_url: http://127.0.0.1:3000/tenants/auth/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:3000/tenants/auth/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://127.0.0.1:3000/tenants/auth/verification
      use: code
      after:
        default_browser_return_url: http://127.0.0.1:3000/tenants/auth/settings

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:3000/tenants/auth/login

    login:
      ui_url: http://127.0.0.1:3000/tenants/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:3000/tenants/auth/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtp://mail-server:1025?disable_starttls=true
