// Code generated by qtc from "apiKeysCreatePage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line transports/webui/views/apiKeysCreatePage.qtpl:1
package views

//line transports/webui/views/apiKeysCreatePage.qtpl:1
import "strings"

//line transports/webui/views/apiKeysCreatePage.qtpl:2
import "github.com/samber/lo"

//line transports/webui/views/apiKeysCreatePage.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line transports/webui/views/apiKeysCreatePage.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line transports/webui/views/apiKeysCreatePage.qtpl:3
func (p *APIKeysCreatePage) StreamBody(qw422016 *qt422016.Writer) {
//line transports/webui/views/apiKeysCreatePage.qtpl:3
	qw422016.N().S(`
<div class="w-full bg-white">
    <header class="w-full flex items-center justify-between border-b py-2 px-4 text-sm text-slate-700">
        <section>
            Create API Key
        </section>
    </header>
    <form 
        id="apiKeyCreateForm" 
        class="p-4 gap-4 grid lg:grid-cols-1"
        method="POST"
        action="`)
//line transports/webui/views/apiKeysCreatePage.qtpl:14
	qw422016.E().S(U("/api-keys/create"))
//line transports/webui/views/apiKeysCreatePage.qtpl:14
	qw422016.N().S(`"
    >
        <fieldset>
            <label for="api-key-tenant" class="ml-1 -mb-1 block"><small
                    class="text-xs text-slate-500">Tenant</small></label>
            <select name="api-key-tenant" id="api-key-tenant"
                class="block w-full px-2 py-1 border rounded-md bg-white placeholder:text-slate-600" required>
                `)
//line transports/webui/views/apiKeysCreatePage.qtpl:21
	StreamRenderTenantSelect(qw422016, p.Tenants)
//line transports/webui/views/apiKeysCreatePage.qtpl:21
	qw422016.N().S(`
                <select />
        </fieldset>
        <fieldset>
            <label for="api-key-name" class="ml-1 -mb-1 block"><small
                    class="text-xs text-slate-500">Name</small></label>
            <input type="text" name="api-key-name" id="api-key-name"
                class="block w-full px-2 py-1 border rounded-md bg-white placeholder:text-slate-600" required />
        </fieldset>
        <fieldset>
            <label for="api-key-expiry" class="ml-1 -mb-1 block"><small class="text-xs text-slate-500">Expires</small>
                <input type="checkbox" _="on click toggle .hidden on #api-key-expiry"
                    class="h-4 w-4 ml-2 text-secondary-500 cursor-pointer">
            </label>
            <input _="init get formattedDateTomorrow() then set @min to it on me" type="date" min=""
                name="api-key-expiry" id="api-key-expiry"
                class="w-full px-2 py-1 border rounded-md bg-white placeholder:text-slate-600 hidden" />
        </fieldset>
        <fieldset>
            <label></label>
            `)
//line transports/webui/views/apiKeysCreatePage.qtpl:41
	StreamRenderPermissionTables(qw422016, p.Permissions)
//line transports/webui/views/apiKeysCreatePage.qtpl:41
	qw422016.N().S(`
        </fieldset>
        <div class="col-span-full">
            <input
                _="on change from closest <form/>
                for elt in <[required]/>
                  if the elt's value is empty
                    add @disabled then exit
                  end
                end
                for el in .permission-checkbox.checked
                    log el
                    if el === true
                        remove @disabled then exit
                    end
                end
                add @disabled"
                disabled type="submit" id="api-key-create-button"
                class="cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed text-sm bg-emerald-400 hover:bg-emerald-500 text-white border border-emerald-500 rounded px-2 py-1"
                value="Generate new API Key" />
        </div>
    </form>
    <script type="text/javascript">
        function formattedDateTomorrow() {
            var currentDate = new Date();
            currentDate.setDate(currentDate.getDate() + 1);
            return currentDate.toISOString().split("T")[0];
        }
    </script>
</div>
`)
//line transports/webui/views/apiKeysCreatePage.qtpl:71
}

//line transports/webui/views/apiKeysCreatePage.qtpl:71
func (p *APIKeysCreatePage) WriteBody(qq422016 qtio422016.Writer) {
//line transports/webui/views/apiKeysCreatePage.qtpl:71
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transports/webui/views/apiKeysCreatePage.qtpl:71
	p.StreamBody(qw422016)
//line transports/webui/views/apiKeysCreatePage.qtpl:71
	qt422016.ReleaseWriter(qw422016)
//line transports/webui/views/apiKeysCreatePage.qtpl:71
}

//line transports/webui/views/apiKeysCreatePage.qtpl:71
func (p *APIKeysCreatePage) Body() string {
//line transports/webui/views/apiKeysCreatePage.qtpl:71
	qb422016 := qt422016.AcquireByteBuffer()
//line transports/webui/views/apiKeysCreatePage.qtpl:71
	p.WriteBody(qb422016)
//line transports/webui/views/apiKeysCreatePage.qtpl:71
	qs422016 := string(qb422016.B)
//line transports/webui/views/apiKeysCreatePage.qtpl:71
	qt422016.ReleaseByteBuffer(qb422016)
//line transports/webui/views/apiKeysCreatePage.qtpl:71
	return qs422016
//line transports/webui/views/apiKeysCreatePage.qtpl:71
}

//line transports/webui/views/apiKeysCreatePage.qtpl:73
func StreamRenderTenantSelect(qw422016 *qt422016.Writer, tenants []TenantInfo) {
//line transports/webui/views/apiKeysCreatePage.qtpl:73
	qw422016.N().S(`
`)
//line transports/webui/views/apiKeysCreatePage.qtpl:74
	for _, tenant := range tenants {
//line transports/webui/views/apiKeysCreatePage.qtpl:74
		qw422016.N().S(`
<option value="`)
//line transports/webui/views/apiKeysCreatePage.qtpl:75
		qw422016.N().D(tenant.ID)
//line transports/webui/views/apiKeysCreatePage.qtpl:75
		qw422016.N().S(`">`)
//line transports/webui/views/apiKeysCreatePage.qtpl:75
		qw422016.E().S(tenant.Name)
//line transports/webui/views/apiKeysCreatePage.qtpl:75
		qw422016.N().S(`</option>
`)
//line transports/webui/views/apiKeysCreatePage.qtpl:76
	}
//line transports/webui/views/apiKeysCreatePage.qtpl:76
	qw422016.N().S(`
`)
//line transports/webui/views/apiKeysCreatePage.qtpl:77
}

//line transports/webui/views/apiKeysCreatePage.qtpl:77
func WriteRenderTenantSelect(qq422016 qtio422016.Writer, tenants []TenantInfo) {
//line transports/webui/views/apiKeysCreatePage.qtpl:77
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transports/webui/views/apiKeysCreatePage.qtpl:77
	StreamRenderTenantSelect(qw422016, tenants)
//line transports/webui/views/apiKeysCreatePage.qtpl:77
	qt422016.ReleaseWriter(qw422016)
//line transports/webui/views/apiKeysCreatePage.qtpl:77
}

//line transports/webui/views/apiKeysCreatePage.qtpl:77
func RenderTenantSelect(tenants []TenantInfo) string {
//line transports/webui/views/apiKeysCreatePage.qtpl:77
	qb422016 := qt422016.AcquireByteBuffer()
//line transports/webui/views/apiKeysCreatePage.qtpl:77
	WriteRenderTenantSelect(qb422016, tenants)
//line transports/webui/views/apiKeysCreatePage.qtpl:77
	qs422016 := string(qb422016.B)
//line transports/webui/views/apiKeysCreatePage.qtpl:77
	qt422016.ReleaseByteBuffer(qb422016)
//line transports/webui/views/apiKeysCreatePage.qtpl:77
	return qs422016
//line transports/webui/views/apiKeysCreatePage.qtpl:77
}

//line transports/webui/views/apiKeysCreatePage.qtpl:79
func StreamRenderPermissionTables(qw422016 *qt422016.Writer, permissions map[OrderedMapKey][]APIKeysPermission) {
//line transports/webui/views/apiKeysCreatePage.qtpl:79
	qw422016.N().S(`
`)
//line transports/webui/views/apiKeysCreatePage.qtpl:80
	for i := 0; i < len(permissions); i++ {
//line transports/webui/views/apiKeysCreatePage.qtpl:80
		qw422016.N().S(`
`)
//line transports/webui/views/apiKeysCreatePage.qtpl:82
		category, _ := lo.FindKeyBy(permissions, func(key OrderedMapKey, value []APIKeysPermission) bool {
			return key.Index == i
		})

//line transports/webui/views/apiKeysCreatePage.qtpl:85
		qw422016.N().S(`
<table class="min-w-full bg-white border border-gray-300 mb-2">
    <thead>
        <tr class="bg-secondary-400 text-secondary-100">
            <th class="py-2 px-4" colspan="2">
                <span class="ml-2 float-left">`)
//line transports/webui/views/apiKeysCreatePage.qtpl:90
		qw422016.E().S(category.Value)
//line transports/webui/views/apiKeysCreatePage.qtpl:90
		qw422016.N().S(`</span>
            </th>
            <th class="py-2 px-4">
                <input type="checkbox" _="on click set .checkbox-`)
//line transports/webui/views/apiKeysCreatePage.qtpl:93
		qw422016.E().S(htmlFriendlyName(category.Value))
//line transports/webui/views/apiKeysCreatePage.qtpl:93
		qw422016.N().S(`.checked to my.checked"
                    class="h-4 w-4 text-secondary-500 cursor-pointer float-right">
            </th>
        </tr>
    </thead>
    <tbody>
        `)
//line transports/webui/views/apiKeysCreatePage.qtpl:99
		for _, permission := range permissions[category] {
//line transports/webui/views/apiKeysCreatePage.qtpl:99
			qw422016.N().S(`
        <tr>
            <td class="py-2 px-4 w-1/6">
                `)
//line transports/webui/views/apiKeysCreatePage.qtpl:102
			qw422016.E().S(permission.Name)
//line transports/webui/views/apiKeysCreatePage.qtpl:102
			qw422016.N().S(`
            </td>
            <td class="py-2 px-4 w-4/6">
                `)
//line transports/webui/views/apiKeysCreatePage.qtpl:105
			qw422016.E().S(permission.Description)
//line transports/webui/views/apiKeysCreatePage.qtpl:105
			qw422016.N().S(`
            </td>
            <td class="py-2 px-4 w-1/6">
                <input type="checkbox" name="api-key-permissions" value="`)
//line transports/webui/views/apiKeysCreatePage.qtpl:108
			qw422016.E().S(permission.Name)
//line transports/webui/views/apiKeysCreatePage.qtpl:108
			qw422016.N().S(`"
                    class="h-4 w-4 text-secondary-500 permission-checkbox cursor-pointer float-right checkbox-`)
//line transports/webui/views/apiKeysCreatePage.qtpl:109
			qw422016.E().S(htmlFriendlyName(category.Value))
//line transports/webui/views/apiKeysCreatePage.qtpl:109
			qw422016.N().S(`">
            </td>
        </tr>
        `)
//line transports/webui/views/apiKeysCreatePage.qtpl:112
		}
//line transports/webui/views/apiKeysCreatePage.qtpl:112
		qw422016.N().S(`
    </tbody>
</table>
`)
//line transports/webui/views/apiKeysCreatePage.qtpl:115
	}
//line transports/webui/views/apiKeysCreatePage.qtpl:115
	qw422016.N().S(`
`)
//line transports/webui/views/apiKeysCreatePage.qtpl:116
}

//line transports/webui/views/apiKeysCreatePage.qtpl:116
func WriteRenderPermissionTables(qq422016 qtio422016.Writer, permissions map[OrderedMapKey][]APIKeysPermission) {
//line transports/webui/views/apiKeysCreatePage.qtpl:116
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transports/webui/views/apiKeysCreatePage.qtpl:116
	StreamRenderPermissionTables(qw422016, permissions)
//line transports/webui/views/apiKeysCreatePage.qtpl:116
	qt422016.ReleaseWriter(qw422016)
//line transports/webui/views/apiKeysCreatePage.qtpl:116
}

//line transports/webui/views/apiKeysCreatePage.qtpl:116
func RenderPermissionTables(permissions map[OrderedMapKey][]APIKeysPermission) string {
//line transports/webui/views/apiKeysCreatePage.qtpl:116
	qb422016 := qt422016.AcquireByteBuffer()
//line transports/webui/views/apiKeysCreatePage.qtpl:116
	WriteRenderPermissionTables(qb422016, permissions)
//line transports/webui/views/apiKeysCreatePage.qtpl:116
	qs422016 := string(qb422016.B)
//line transports/webui/views/apiKeysCreatePage.qtpl:116
	qt422016.ReleaseByteBuffer(qb422016)
//line transports/webui/views/apiKeysCreatePage.qtpl:116
	return qs422016
//line transports/webui/views/apiKeysCreatePage.qtpl:116
}

//line transports/webui/views/apiKeysCreatePage.qtpl:119
type APIKeysCreatePage struct {
	Base
	Tenants     []TenantInfo
	Permissions map[OrderedMapKey][]APIKeysPermission
}

type APIKeysPermission struct {
	Name        string
	Description string
}

type OrderedMapKey struct {
	Index int
	Value string
}

func htmlFriendlyName(src string) string {
	return strings.ReplaceAll(src, " ", "")
}
