// Code generated by qtc from "apiKeysPage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/apiKeysPage.qtpl:1
package views

//line views/apiKeysPage.qtpl:1
import "time"

//line views/apiKeysPage.qtpl:2
import "sensorbucket.nl/sensorbucket/pkg/layout"

//line views/apiKeysPage.qtpl:3
import "strings"

//line views/apiKeysPage.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/apiKeysPage.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/apiKeysPage.qtpl:4
func (p *APIKeysPage) StreamBody(qw422016 *qt422016.Writer) {
//line views/apiKeysPage.qtpl:4
	qw422016.N().S(`
<div class="w-full xl:w-2/3 mx-auto bg-white border rounded-md">
    `)
//line views/apiKeysPage.qtpl:6
	if p.CreatedAPIKey != "" {
//line views/apiKeysPage.qtpl:6
		qw422016.N().S(`
    <div id="api-key-create-result" class="p-3">
        <div class="bg-orange-100 border-l-4 border-orange-400 text-orange-600 p-4" role="alert">
            <div class="flex w-full">
                <div class="py-1"><svg class="fill-current h-6 w-6 text-orange-600 mr-4"
                        xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                        <path
                            d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z" />
                    </svg></div>
                <div class="w-full">
                    <p class="text-sm font-bold">This is your API Key, please copy your API Key immediately as it
                        will not be shown again</p>
                    <br />
                    <div class="flex justify-start">
                        <p id="api-key-result-value" class="text-sm w-full truncate">
                            `)
//line views/apiKeysPage.qtpl:21
		qw422016.E().S(p.CreatedAPIKey)
//line views/apiKeysPage.qtpl:21
		qw422016.N().S(`
                        </p>
                        <button onclick="copyAPIKeyToClipboard()"
                            class="text-sm ml-1 bg-orange-400 hover:bg-orange-500 text-white border border-orange-500 rounded px-2 py-1">
                            Copy
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            function copyAPIKeyToClipboard() {
                const text = document.getElementById("api-key-result-value").innerText;
                navigator.clipboard.writeText(text);
                showSnackbar("API key copied to clipboard!", snackbarSuccess);
            }
        </script>

    </div>
    `)
//line views/apiKeysPage.qtpl:40
	}
//line views/apiKeysPage.qtpl:40
	qw422016.N().S(`
    <header class="w-full flex items-center justify-between border-b py-2 px-4 text-sm text-slate-700">
        <section>
            API Keys
        </section>
        <section class="flex gap-2">
            <button
                class="text-xs bg-emerald-400 hover:bg-emerald-500 text-white border border-emerald-500 rounded px-2 py-1"
                hx-get="`)
//line views/apiKeysPage.qtpl:48
	qw422016.E().S(layout.U(" /api-keys/create"))
//line views/apiKeysPage.qtpl:48
	qw422016.N().S(`" hx-target="main" hx-push-url="true">
                Create
            </button>
        </section>
    </header>
    <div> `)
//line views/apiKeysPage.qtpl:53
	StreamRenderAPIKeyTable(qw422016, p.Tenants, p.TenantsNextPage)
//line views/apiKeysPage.qtpl:53
	qw422016.N().S(`</div>
</div>
`)
//line views/apiKeysPage.qtpl:55
}

//line views/apiKeysPage.qtpl:55
func (p *APIKeysPage) WriteBody(qq422016 qtio422016.Writer) {
//line views/apiKeysPage.qtpl:55
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/apiKeysPage.qtpl:55
	p.StreamBody(qw422016)
//line views/apiKeysPage.qtpl:55
	qt422016.ReleaseWriter(qw422016)
//line views/apiKeysPage.qtpl:55
}

//line views/apiKeysPage.qtpl:55
func (p *APIKeysPage) Body() string {
//line views/apiKeysPage.qtpl:55
	qb422016 := qt422016.AcquireByteBuffer()
//line views/apiKeysPage.qtpl:55
	p.WriteBody(qb422016)
//line views/apiKeysPage.qtpl:55
	qs422016 := string(qb422016.B)
//line views/apiKeysPage.qtpl:55
	qt422016.ReleaseByteBuffer(qb422016)
//line views/apiKeysPage.qtpl:55
	return qs422016
//line views/apiKeysPage.qtpl:55
}

//line views/apiKeysPage.qtpl:57
func StreamRenderAPIKeyTable(qw422016 *qt422016.Writer, tenants []TenantInfo, tenantsNextPage string) {
//line views/apiKeysPage.qtpl:57
	qw422016.N().S(`
`)
//line views/apiKeysPage.qtpl:58
	for _, tenant := range tenants {
//line views/apiKeysPage.qtpl:58
		qw422016.N().S(`
<table class="w-full text-sm border-separate border-spacing-0 mb-3" id="device-table">
    <thead>
        `)
//line views/apiKeysPage.qtpl:61
		StreamRenderAPIKeyRowHeading(qw422016, tenant)
//line views/apiKeysPage.qtpl:61
		qw422016.N().S(`
    </thead>
    <tbody _="init toggle the *display of me" id="tenant-table-`)
//line views/apiKeysPage.qtpl:63
		qw422016.N().D(tenant.ID)
//line views/apiKeysPage.qtpl:63
		qw422016.N().S(`">
    </tbody>
</table>
`)
//line views/apiKeysPage.qtpl:66
	}
//line views/apiKeysPage.qtpl:66
	qw422016.N().S(`
`)
//line views/apiKeysPage.qtpl:67
}

//line views/apiKeysPage.qtpl:67
func WriteRenderAPIKeyTable(qq422016 qtio422016.Writer, tenants []TenantInfo, tenantsNextPage string) {
//line views/apiKeysPage.qtpl:67
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/apiKeysPage.qtpl:67
	StreamRenderAPIKeyTable(qw422016, tenants, tenantsNextPage)
//line views/apiKeysPage.qtpl:67
	qt422016.ReleaseWriter(qw422016)
//line views/apiKeysPage.qtpl:67
}

//line views/apiKeysPage.qtpl:67
func RenderAPIKeyTable(tenants []TenantInfo, tenantsNextPage string) string {
//line views/apiKeysPage.qtpl:67
	qb422016 := qt422016.AcquireByteBuffer()
//line views/apiKeysPage.qtpl:67
	WriteRenderAPIKeyTable(qb422016, tenants, tenantsNextPage)
//line views/apiKeysPage.qtpl:67
	qs422016 := string(qb422016.B)
//line views/apiKeysPage.qtpl:67
	qt422016.ReleaseByteBuffer(qb422016)
//line views/apiKeysPage.qtpl:67
	return qs422016
//line views/apiKeysPage.qtpl:67
}

//line views/apiKeysPage.qtpl:69
func StreamRenderAPIKeyRowHeading(qw422016 *qt422016.Writer, tenant TenantInfo) {
//line views/apiKeysPage.qtpl:69
	qw422016.N().S(`
<tr class="cursor-pointer h-10 border-b font-bold text-secondary-100 bg-secondary-400" hx-trigger="click once"
    hx-get="/api-keys/table?tenant_id=`)
//line views/apiKeysPage.qtpl:71
	qw422016.N().D(tenant.ID)
//line views/apiKeysPage.qtpl:71
	qw422016.N().S(`" hx-target="#tenant-table-`)
//line views/apiKeysPage.qtpl:71
	qw422016.N().D(tenant.ID)
//line views/apiKeysPage.qtpl:71
	qw422016.N().S(`" hx-swap="beforeend"
    _="on click toggle the *display of #tenant-table-`)
//line views/apiKeysPage.qtpl:72
	qw422016.N().D(tenant.ID)
//line views/apiKeysPage.qtpl:72
	qw422016.N().S(` then toggle .rotate-180 on #collapse-`)
//line views/apiKeysPage.qtpl:72
	qw422016.N().D(tenant.ID)
//line views/apiKeysPage.qtpl:72
	qw422016.N().S(`">
    <td class="px-4" colspan="4">
        <span>`)
//line views/apiKeysPage.qtpl:74
	qw422016.E().S(tenant.Name)
//line views/apiKeysPage.qtpl:74
	qw422016.N().S(`</span>
    </td>
    <td colspan="1">
        <iconify-icon id="collapse-`)
//line views/apiKeysPage.qtpl:77
	qw422016.N().D(tenant.ID)
//line views/apiKeysPage.qtpl:77
	qw422016.N().S(`" icon="ooui:collapse"
            class="px-4 float-right rotate-180"></iconify-icon>
    </td>
</tr>
`)
//line views/apiKeysPage.qtpl:81
}

//line views/apiKeysPage.qtpl:81
func WriteRenderAPIKeyRowHeading(qq422016 qtio422016.Writer, tenant TenantInfo) {
//line views/apiKeysPage.qtpl:81
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/apiKeysPage.qtpl:81
	StreamRenderAPIKeyRowHeading(qw422016, tenant)
//line views/apiKeysPage.qtpl:81
	qt422016.ReleaseWriter(qw422016)
//line views/apiKeysPage.qtpl:81
}

//line views/apiKeysPage.qtpl:81
func RenderAPIKeyRowHeading(tenant TenantInfo) string {
//line views/apiKeysPage.qtpl:81
	qb422016 := qt422016.AcquireByteBuffer()
//line views/apiKeysPage.qtpl:81
	WriteRenderAPIKeyRowHeading(qb422016, tenant)
//line views/apiKeysPage.qtpl:81
	qs422016 := string(qb422016.B)
//line views/apiKeysPage.qtpl:81
	qt422016.ReleaseByteBuffer(qb422016)
//line views/apiKeysPage.qtpl:81
	return qs422016
//line views/apiKeysPage.qtpl:81
}

//line views/apiKeysPage.qtpl:83
func StreamRenderAPIKeyRows(qw422016 *qt422016.Writer, keys []APIKey, nextPage string) {
//line views/apiKeysPage.qtpl:83
	qw422016.N().S(`
`)
//line views/apiKeysPage.qtpl:84
	for _, key := range keys {
//line views/apiKeysPage.qtpl:84
		qw422016.N().S(`
<tr class="hover:bg-slate-50 group key w-full">
    <td title="`)
//line views/apiKeysPage.qtpl:86
		qw422016.E().S(key.Name)
//line views/apiKeysPage.qtpl:86
		qw422016.N().S(`" class="px-4 h-10 border-b w-[4em] max-w-[4em] truncate">`)
//line views/apiKeysPage.qtpl:86
		qw422016.E().S(key.Name)
//line views/apiKeysPage.qtpl:86
		qw422016.N().S(`</td>
    <td class="px-4 h-10 border-b w-[2em] max-w-[2em] truncate">`)
//line views/apiKeysPage.qtpl:87
		qw422016.E().S(key.Created.Format("02/01/2006"))
//line views/apiKeysPage.qtpl:87
		qw422016.N().S(`</td>
    <td class="px-4 h-10 border-b w-[2em] max-w-[2em] truncate">
        `)
//line views/apiKeysPage.qtpl:89
		if key.ExpirationDate != nil {
//line views/apiKeysPage.qtpl:89
			qw422016.N().S(`
        `)
//line views/apiKeysPage.qtpl:90
			qw422016.E().S(key.ExpirationDate.Format("02/01/2006"))
//line views/apiKeysPage.qtpl:90
			qw422016.N().S(`
        `)
//line views/apiKeysPage.qtpl:91
		} else {
//line views/apiKeysPage.qtpl:91
			qw422016.N().S(`
        -
        `)
//line views/apiKeysPage.qtpl:93
		}
//line views/apiKeysPage.qtpl:93
		qw422016.N().S(`
    </td>
    <td class="px-4 h-10 border-b truncate w-[1em] max-w-[1em]">
        `)
//line views/apiKeysPage.qtpl:96
		qw422016.E().S(strings.Join(key.Permissions, ", "))
//line views/apiKeysPage.qtpl:96
		qw422016.N().S(`
    </td>
    <td class="px-4 h-10 border-b w-[1em] max-w-[1em]">
        <button hx-confirm="Are you sure you want to revoke API key with name `)
//line views/apiKeysPage.qtpl:99
		qw422016.E().S(key.Name)
//line views/apiKeysPage.qtpl:99
		qw422016.N().S(`?"
            hx-delete="/api-keys/revoke/`)
//line views/apiKeysPage.qtpl:100
		qw422016.N().D(key.ID)
//line views/apiKeysPage.qtpl:100
		qw422016.N().S(`" hx-trigger="click once" hx-target="closest tr"
            hx-swap="innerHTML"
            class="float-right text-xs bg-red-400 hover:bg-red-500 text-white border border-red-500 rounded px-2 py-1">
            Revoke
        </button>
    </td>
</tr>
`)
//line views/apiKeysPage.qtpl:107
	}
//line views/apiKeysPage.qtpl:107
	qw422016.N().S(`
`)
//line views/apiKeysPage.qtpl:108
	if nextPage != "" {
//line views/apiKeysPage.qtpl:108
		qw422016.N().S(`
<tr hx-trigger="click once" hx-get="`)
//line views/apiKeysPage.qtpl:109
		qw422016.E().S(nextPage)
//line views/apiKeysPage.qtpl:109
		qw422016.N().S(`" hx-swap="outerHTML" class="cursor-pointer key">
    <td class="underline text-sky-600 p-1 text-center" colspan="5">
        <span>Load more...</span>
    </td>
</tr>
`)
//line views/apiKeysPage.qtpl:114
	} else if len(keys) == 0 {
//line views/apiKeysPage.qtpl:114
		qw422016.N().S(`
<tr>
    <td class="italic p-3 text-center" colspan="5">
        <span>No more API keys for this organisation...</span>
    </td>
</tr>
`)
//line views/apiKeysPage.qtpl:120
	}
//line views/apiKeysPage.qtpl:120
	qw422016.N().S(`
`)
//line views/apiKeysPage.qtpl:121
}

//line views/apiKeysPage.qtpl:121
func WriteRenderAPIKeyRows(qq422016 qtio422016.Writer, keys []APIKey, nextPage string) {
//line views/apiKeysPage.qtpl:121
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/apiKeysPage.qtpl:121
	StreamRenderAPIKeyRows(qw422016, keys, nextPage)
//line views/apiKeysPage.qtpl:121
	qt422016.ReleaseWriter(qw422016)
//line views/apiKeysPage.qtpl:121
}

//line views/apiKeysPage.qtpl:121
func RenderAPIKeyRows(keys []APIKey, nextPage string) string {
//line views/apiKeysPage.qtpl:121
	qb422016 := qt422016.AcquireByteBuffer()
//line views/apiKeysPage.qtpl:121
	WriteRenderAPIKeyRows(qb422016, keys, nextPage)
//line views/apiKeysPage.qtpl:121
	qs422016 := string(qb422016.B)
//line views/apiKeysPage.qtpl:121
	qt422016.ReleaseByteBuffer(qb422016)
//line views/apiKeysPage.qtpl:121
	return qs422016
//line views/apiKeysPage.qtpl:121
}

//line views/apiKeysPage.qtpl:124
type APIKeysPage struct {
	layout.BasePage
	Tenants         []TenantInfo
	TenantsNextPage string
	CreatedAPIKey   string
}

type TenantInfo struct {
	ID   int
	Name string
}

type APIKey struct {
	ID             int
	TenantID       int
	Name           string
	ExpirationDate *time.Time
	Permissions    []string
	Created        time.Time
}
