// Code generated by qtc from "elements.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line transports/webui/views/elements.qtpl:1
package views

//line transports/webui/views/elements.qtpl:1
import (
	ory "github.com/ory/client-go"
	"github.com/samber/lo"
)

//line transports/webui/views/elements.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line transports/webui/views/elements.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line transports/webui/views/elements.qtpl:6
func streamrenderNode(qw422016 *qt422016.Writer, n ory.UiNode) {
//line transports/webui/views/elements.qtpl:6
	qw422016.N().S(`
    `)
//line transports/webui/views/elements.qtpl:7
	switch attr := n.Attributes.GetActualInstance().(type) {
//line transports/webui/views/elements.qtpl:8
	case *ory.UiNodeInputAttributes:
//line transports/webui/views/elements.qtpl:8
		qw422016.N().S(`
            `)
//line transports/webui/views/elements.qtpl:9
		streamrenderInputNode(qw422016, n, *attr)
//line transports/webui/views/elements.qtpl:9
		qw422016.N().S(`
        `)
//line transports/webui/views/elements.qtpl:10
	case *ory.UiNodeImageAttributes:
//line transports/webui/views/elements.qtpl:10
		qw422016.N().S(`
            `)
//line transports/webui/views/elements.qtpl:11
		streamrenderImageNode(qw422016, n, *attr)
//line transports/webui/views/elements.qtpl:11
		qw422016.N().S(`
    `)
//line transports/webui/views/elements.qtpl:12
	}
//line transports/webui/views/elements.qtpl:12
	qw422016.N().S(`
`)
//line transports/webui/views/elements.qtpl:13
}

//line transports/webui/views/elements.qtpl:13
func writerenderNode(qq422016 qtio422016.Writer, n ory.UiNode) {
//line transports/webui/views/elements.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transports/webui/views/elements.qtpl:13
	streamrenderNode(qw422016, n)
//line transports/webui/views/elements.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line transports/webui/views/elements.qtpl:13
}

//line transports/webui/views/elements.qtpl:13
func renderNode(n ory.UiNode) string {
//line transports/webui/views/elements.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
//line transports/webui/views/elements.qtpl:13
	writerenderNode(qb422016, n)
//line transports/webui/views/elements.qtpl:13
	qs422016 := string(qb422016.B)
//line transports/webui/views/elements.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
//line transports/webui/views/elements.qtpl:13
	return qs422016
//line transports/webui/views/elements.qtpl:13
}

//line transports/webui/views/elements.qtpl:15
func streamrenderImageNode(qw422016 *qt422016.Writer, n ory.UiNode, attr ory.UiNodeImageAttributes) {
//line transports/webui/views/elements.qtpl:15
	qw422016.N().S(`
    <img
        src="`)
//line transports/webui/views/elements.qtpl:17
	qw422016.E().S(attr.GetSrc())
//line transports/webui/views/elements.qtpl:17
	qw422016.N().S(`"
        id="`)
//line transports/webui/views/elements.qtpl:18
	qw422016.E().S(attr.GetId())
//line transports/webui/views/elements.qtpl:18
	qw422016.N().S(`"
        width="`)
//line transports/webui/views/elements.qtpl:19
	qw422016.N().DL(attr.GetWidth())
//line transports/webui/views/elements.qtpl:19
	qw422016.N().S(`"
        height="`)
//line transports/webui/views/elements.qtpl:20
	qw422016.N().DL(attr.GetHeight())
//line transports/webui/views/elements.qtpl:20
	qw422016.N().S(`"
    />
`)
//line transports/webui/views/elements.qtpl:22
}

//line transports/webui/views/elements.qtpl:22
func writerenderImageNode(qq422016 qtio422016.Writer, n ory.UiNode, attr ory.UiNodeImageAttributes) {
//line transports/webui/views/elements.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transports/webui/views/elements.qtpl:22
	streamrenderImageNode(qw422016, n, attr)
//line transports/webui/views/elements.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line transports/webui/views/elements.qtpl:22
}

//line transports/webui/views/elements.qtpl:22
func renderImageNode(n ory.UiNode, attr ory.UiNodeImageAttributes) string {
//line transports/webui/views/elements.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
//line transports/webui/views/elements.qtpl:22
	writerenderImageNode(qb422016, n, attr)
//line transports/webui/views/elements.qtpl:22
	qs422016 := string(qb422016.B)
//line transports/webui/views/elements.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
//line transports/webui/views/elements.qtpl:22
	return qs422016
//line transports/webui/views/elements.qtpl:22
}

//line transports/webui/views/elements.qtpl:24
func streamrenderInputNode(qw422016 *qt422016.Writer, n ory.UiNode, attr ory.UiNodeInputAttributes) {
//line transports/webui/views/elements.qtpl:24
	qw422016.N().S(`
    `)
//line transports/webui/views/elements.qtpl:25
	if attr.GetType() == "submit" {
//line transports/webui/views/elements.qtpl:25
		qw422016.N().S(`
    <button 
        class="text-center p-2 bg-secondary-500 text-white"
        `)
//line transports/webui/views/elements.qtpl:28
		streamrenderInputNodeAttributes(qw422016, n, attr)
//line transports/webui/views/elements.qtpl:28
		qw422016.N().S(`
        >`)
//line transports/webui/views/elements.qtpl:29
		qw422016.E().S(n.Meta.GetLabel().Text)
//line transports/webui/views/elements.qtpl:29
		qw422016.N().S(`</button>
    `)
//line transports/webui/views/elements.qtpl:30
		return
//line transports/webui/views/elements.qtpl:31
	}
//line transports/webui/views/elements.qtpl:31
	qw422016.N().S(`
    <fieldset>
        `)
//line transports/webui/views/elements.qtpl:33
	if label, ok := n.Meta.GetLabelOk(); ok {
//line transports/webui/views/elements.qtpl:33
		qw422016.N().S(`
        <label for="`)
//line transports/webui/views/elements.qtpl:34
		qw422016.E().S(attr.GetName())
//line transports/webui/views/elements.qtpl:34
		qw422016.N().S(`" class="flex flex-col text-sm">
            <span>`)
//line transports/webui/views/elements.qtpl:35
		qw422016.E().S(label.Text)
//line transports/webui/views/elements.qtpl:35
		qw422016.N().S(`</span>
        `)
//line transports/webui/views/elements.qtpl:36
	}
//line transports/webui/views/elements.qtpl:36
	qw422016.N().S(`
        <input 
            class="border px-2 py-1"
            `)
//line transports/webui/views/elements.qtpl:39
	streamrenderInputNodeAttributes(qw422016, n, attr)
//line transports/webui/views/elements.qtpl:39
	qw422016.N().S(`
            />
        `)
//line transports/webui/views/elements.qtpl:41
	if n.Meta.HasLabel() {
//line transports/webui/views/elements.qtpl:41
		qw422016.N().S(`
        </label>
        `)
//line transports/webui/views/elements.qtpl:43
	}
//line transports/webui/views/elements.qtpl:43
	qw422016.N().S(`
        `)
//line transports/webui/views/elements.qtpl:44
	for _, msg := range n.GetMessages() {
//line transports/webui/views/elements.qtpl:44
		qw422016.N().S(`
            <span style="color: red;">`)
//line transports/webui/views/elements.qtpl:45
		qw422016.E().S(msg.GetText())
//line transports/webui/views/elements.qtpl:45
		qw422016.N().S(`</span>
        `)
//line transports/webui/views/elements.qtpl:46
	}
//line transports/webui/views/elements.qtpl:46
	qw422016.N().S(`
    </fieldset>
`)
//line transports/webui/views/elements.qtpl:48
}

//line transports/webui/views/elements.qtpl:48
func writerenderInputNode(qq422016 qtio422016.Writer, n ory.UiNode, attr ory.UiNodeInputAttributes) {
//line transports/webui/views/elements.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transports/webui/views/elements.qtpl:48
	streamrenderInputNode(qw422016, n, attr)
//line transports/webui/views/elements.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line transports/webui/views/elements.qtpl:48
}

//line transports/webui/views/elements.qtpl:48
func renderInputNode(n ory.UiNode, attr ory.UiNodeInputAttributes) string {
//line transports/webui/views/elements.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line transports/webui/views/elements.qtpl:48
	writerenderInputNode(qb422016, n, attr)
//line transports/webui/views/elements.qtpl:48
	qs422016 := string(qb422016.B)
//line transports/webui/views/elements.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line transports/webui/views/elements.qtpl:48
	return qs422016
//line transports/webui/views/elements.qtpl:48
}

//line transports/webui/views/elements.qtpl:50
func streamrenderInputNodeAttributes(qw422016 *qt422016.Writer, n ory.UiNode, attr ory.UiNodeInputAttributes) {
//line transports/webui/views/elements.qtpl:50
	qw422016.N().S(`
    name="`)
//line transports/webui/views/elements.qtpl:51
	qw422016.E().S(attr.GetName())
//line transports/webui/views/elements.qtpl:51
	qw422016.N().S(`"
    type="`)
//line transports/webui/views/elements.qtpl:52
	qw422016.E().S(attr.GetType())
//line transports/webui/views/elements.qtpl:52
	qw422016.N().S(`"
    `)
//line transports/webui/views/elements.qtpl:53
	if attr.GetAutocomplete() != "" {
//line transports/webui/views/elements.qtpl:53
		qw422016.N().S(`
        autocomplete="`)
//line transports/webui/views/elements.qtpl:54
		qw422016.E().S(attr.GetAutocomplete())
//line transports/webui/views/elements.qtpl:54
		qw422016.N().S(`"
    `)
//line transports/webui/views/elements.qtpl:55
	}
//line transports/webui/views/elements.qtpl:55
	qw422016.N().S(`
    `)
//line transports/webui/views/elements.qtpl:56
	if attr.GetDisabled() {
//line transports/webui/views/elements.qtpl:56
		qw422016.N().S(`
        disabled
    `)
//line transports/webui/views/elements.qtpl:58
	}
//line transports/webui/views/elements.qtpl:58
	qw422016.N().S(`
    `)
//line transports/webui/views/elements.qtpl:59
	if attr.GetRequired() {
//line transports/webui/views/elements.qtpl:59
		qw422016.N().S(`
        required
    `)
//line transports/webui/views/elements.qtpl:61
	}
//line transports/webui/views/elements.qtpl:61
	qw422016.N().S(`
    `)
//line transports/webui/views/elements.qtpl:62
	if attr.GetPattern() != "" {
//line transports/webui/views/elements.qtpl:62
		qw422016.N().S(`
        pattern="`)
//line transports/webui/views/elements.qtpl:63
		qw422016.E().S(attr.GetPattern())
//line transports/webui/views/elements.qtpl:63
		qw422016.N().S(`"
    `)
//line transports/webui/views/elements.qtpl:64
	}
//line transports/webui/views/elements.qtpl:64
	qw422016.N().S(`
    `)
//line transports/webui/views/elements.qtpl:65
	if attr.GetOnclick() != "" {
//line transports/webui/views/elements.qtpl:65
		qw422016.N().S(`
        onclick="`)
//line transports/webui/views/elements.qtpl:66
		qw422016.E().S(attr.GetOnclick())
//line transports/webui/views/elements.qtpl:66
		qw422016.N().S(`"
    `)
//line transports/webui/views/elements.qtpl:67
	}
//line transports/webui/views/elements.qtpl:67
	qw422016.N().S(`
    `)
//line transports/webui/views/elements.qtpl:68
	if attr.Value != nil {
//line transports/webui/views/elements.qtpl:68
		qw422016.N().S(`
        value="`)
//line transports/webui/views/elements.qtpl:69
		qw422016.E().V(attr.Value)
//line transports/webui/views/elements.qtpl:69
		qw422016.N().S(`"
    `)
//line transports/webui/views/elements.qtpl:70
	}
//line transports/webui/views/elements.qtpl:70
	qw422016.N().S(`
    `)
//line transports/webui/views/elements.qtpl:71
	if label, ok := n.Meta.GetLabelOk(); ok && label.GetId() == 1070008 {
//line transports/webui/views/elements.qtpl:71
		qw422016.N().S(`
        formNoValidate
    `)
//line transports/webui/views/elements.qtpl:73
	}
//line transports/webui/views/elements.qtpl:73
	qw422016.N().S(`
`)
//line transports/webui/views/elements.qtpl:74
}

//line transports/webui/views/elements.qtpl:74
func writerenderInputNodeAttributes(qq422016 qtio422016.Writer, n ory.UiNode, attr ory.UiNodeInputAttributes) {
//line transports/webui/views/elements.qtpl:74
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transports/webui/views/elements.qtpl:74
	streamrenderInputNodeAttributes(qw422016, n, attr)
//line transports/webui/views/elements.qtpl:74
	qt422016.ReleaseWriter(qw422016)
//line transports/webui/views/elements.qtpl:74
}

//line transports/webui/views/elements.qtpl:74
func renderInputNodeAttributes(n ory.UiNode, attr ory.UiNodeInputAttributes) string {
//line transports/webui/views/elements.qtpl:74
	qb422016 := qt422016.AcquireByteBuffer()
//line transports/webui/views/elements.qtpl:74
	writerenderInputNodeAttributes(qb422016, n, attr)
//line transports/webui/views/elements.qtpl:74
	qs422016 := string(qb422016.B)
//line transports/webui/views/elements.qtpl:74
	qt422016.ReleaseByteBuffer(qb422016)
//line transports/webui/views/elements.qtpl:74
	return qs422016
//line transports/webui/views/elements.qtpl:74
}

//line transports/webui/views/elements.qtpl:76
func streamrenderGroup(qw422016 *qt422016.Writer, ui ory.UiContainer, group string) {
//line transports/webui/views/elements.qtpl:76
	qw422016.N().S(`
    <form 
        class="flex flex-col space-y-2"
        method="`)
//line transports/webui/views/elements.qtpl:79
	qw422016.E().S(ui.Method)
//line transports/webui/views/elements.qtpl:79
	qw422016.N().S(`" action="`)
//line transports/webui/views/elements.qtpl:79
	qw422016.E().S(ui.Action)
//line transports/webui/views/elements.qtpl:79
	qw422016.N().S(`">
        `)
//line transports/webui/views/elements.qtpl:80
	streamrenderDefaultNodes(qw422016, ui)
//line transports/webui/views/elements.qtpl:80
	qw422016.N().S(`
        `)
//line transports/webui/views/elements.qtpl:81
	for _, n := range filterNodes(ui.Nodes, group) {
//line transports/webui/views/elements.qtpl:81
		qw422016.N().S(`
            `)
//line transports/webui/views/elements.qtpl:82
		streamrenderNode(qw422016, n)
//line transports/webui/views/elements.qtpl:82
		qw422016.N().S(`
        `)
//line transports/webui/views/elements.qtpl:83
	}
//line transports/webui/views/elements.qtpl:83
	qw422016.N().S(`
        `)
//line transports/webui/views/elements.qtpl:84
	for _, msg := range ui.GetMessages() {
//line transports/webui/views/elements.qtpl:84
		qw422016.N().S(`
            <span style="color: red;">`)
//line transports/webui/views/elements.qtpl:85
		qw422016.E().S(msg.GetText())
//line transports/webui/views/elements.qtpl:85
		qw422016.N().S(`</span>
        `)
//line transports/webui/views/elements.qtpl:86
	}
//line transports/webui/views/elements.qtpl:86
	qw422016.N().S(`
    </form>
`)
//line transports/webui/views/elements.qtpl:88
}

//line transports/webui/views/elements.qtpl:88
func writerenderGroup(qq422016 qtio422016.Writer, ui ory.UiContainer, group string) {
//line transports/webui/views/elements.qtpl:88
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transports/webui/views/elements.qtpl:88
	streamrenderGroup(qw422016, ui, group)
//line transports/webui/views/elements.qtpl:88
	qt422016.ReleaseWriter(qw422016)
//line transports/webui/views/elements.qtpl:88
}

//line transports/webui/views/elements.qtpl:88
func renderGroup(ui ory.UiContainer, group string) string {
//line transports/webui/views/elements.qtpl:88
	qb422016 := qt422016.AcquireByteBuffer()
//line transports/webui/views/elements.qtpl:88
	writerenderGroup(qb422016, ui, group)
//line transports/webui/views/elements.qtpl:88
	qs422016 := string(qb422016.B)
//line transports/webui/views/elements.qtpl:88
	qt422016.ReleaseByteBuffer(qb422016)
//line transports/webui/views/elements.qtpl:88
	return qs422016
//line transports/webui/views/elements.qtpl:88
}

//line transports/webui/views/elements.qtpl:90
func streamrenderDefaultNodes(qw422016 *qt422016.Writer, ui ory.UiContainer) {
//line transports/webui/views/elements.qtpl:90
	qw422016.N().S(`
        `)
//line transports/webui/views/elements.qtpl:91
	for _, n := range filterNodes(ui.Nodes, "default") {
//line transports/webui/views/elements.qtpl:91
		qw422016.N().S(`
            `)
//line transports/webui/views/elements.qtpl:92
		streamrenderNode(qw422016, n)
//line transports/webui/views/elements.qtpl:92
		qw422016.N().S(`
        `)
//line transports/webui/views/elements.qtpl:93
	}
//line transports/webui/views/elements.qtpl:93
	qw422016.N().S(`
`)
//line transports/webui/views/elements.qtpl:94
}

//line transports/webui/views/elements.qtpl:94
func writerenderDefaultNodes(qq422016 qtio422016.Writer, ui ory.UiContainer) {
//line transports/webui/views/elements.qtpl:94
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transports/webui/views/elements.qtpl:94
	streamrenderDefaultNodes(qw422016, ui)
//line transports/webui/views/elements.qtpl:94
	qt422016.ReleaseWriter(qw422016)
//line transports/webui/views/elements.qtpl:94
}

//line transports/webui/views/elements.qtpl:94
func renderDefaultNodes(ui ory.UiContainer) string {
//line transports/webui/views/elements.qtpl:94
	qb422016 := qt422016.AcquireByteBuffer()
//line transports/webui/views/elements.qtpl:94
	writerenderDefaultNodes(qb422016, ui)
//line transports/webui/views/elements.qtpl:94
	qs422016 := string(qb422016.B)
//line transports/webui/views/elements.qtpl:94
	qt422016.ReleaseByteBuffer(qb422016)
//line transports/webui/views/elements.qtpl:94
	return qs422016
//line transports/webui/views/elements.qtpl:94
}

//line transports/webui/views/elements.qtpl:97
func filterNodes(n []ory.UiNode, group string) []ory.UiNode {
	return lo.Filter(n, func(n ory.UiNode, _ int) bool {
		return n.GetGroup() == group
	})
}
