// Code generated by qtc from "login.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line transports/webui/views/login.qtpl:1
package views

//line transports/webui/views/login.qtpl:1
import ory "github.com/ory/client-go"

//line transports/webui/views/login.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line transports/webui/views/login.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line transports/webui/views/login.qtpl:2
type Page interface {
//line transports/webui/views/login.qtpl:2
	Body() string
//line transports/webui/views/login.qtpl:2
	StreamBody(qw422016 *qt422016.Writer)
//line transports/webui/views/login.qtpl:2
	WriteBody(qq422016 qtio422016.Writer)
//line transports/webui/views/login.qtpl:2
}

//line transports/webui/views/login.qtpl:6
func StreamLayout(qw422016 *qt422016.Writer, p Page) {
//line transports/webui/views/login.qtpl:6
	qw422016.N().S(`

<!DOCTYPE html>
<html lang="en" class="bg-[#f8fafc]">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="`)
//line transports/webui/views/login.qtpl:14
	qw422016.E().S(U("/static/style.css"))
//line transports/webui/views/login.qtpl:14
	qw422016.N().S(`" />
    </head>
    <body>
        <main class="mt-12 mx-auto w-full md:max-w-[420px] bg-white rounded-md overflow-hidden">
            <header class="bg-secondary-500 h-14 py-3">
                <img src="`)
//line transports/webui/views/login.qtpl:19
	qw422016.E().S(U("/static/logo-white.png"))
//line transports/webui/views/login.qtpl:19
	qw422016.N().S(`" alt="SensorBucket Logo" class="h-full mx-auto" />
            </header>
            <section class="px-6 mb-4 space-y-2">
            `)
//line transports/webui/views/login.qtpl:22
	p.StreamBody(qw422016)
//line transports/webui/views/login.qtpl:22
	qw422016.N().S(`
            </section>
        </main>
    </body>
</html>

`)
//line transports/webui/views/login.qtpl:28
}

//line transports/webui/views/login.qtpl:28
func WriteLayout(qq422016 qtio422016.Writer, p Page) {
//line transports/webui/views/login.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transports/webui/views/login.qtpl:28
	StreamLayout(qw422016, p)
//line transports/webui/views/login.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line transports/webui/views/login.qtpl:28
}

//line transports/webui/views/login.qtpl:28
func Layout(p Page) string {
//line transports/webui/views/login.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
//line transports/webui/views/login.qtpl:28
	WriteLayout(qb422016, p)
//line transports/webui/views/login.qtpl:28
	qs422016 := string(qb422016.B)
//line transports/webui/views/login.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
//line transports/webui/views/login.qtpl:28
	return qs422016
//line transports/webui/views/login.qtpl:28
}

//line transports/webui/views/login.qtpl:31
type LoginPage struct {
	Flow *ory.LoginFlow
}

//line transports/webui/views/login.qtpl:35
func (p LoginPage) StreamBody(qw422016 *qt422016.Writer) {
//line transports/webui/views/login.qtpl:35
	qw422016.N().S(`
    `)
//line transports/webui/views/login.qtpl:36
	if !isMFA(p.Flow) {
//line transports/webui/views/login.qtpl:36
		qw422016.N().S(`
        <h1 class="text-2xl mt-4 ">Login</h1>
        `)
//line transports/webui/views/login.qtpl:38
		streamformStart(qw422016, p.Flow.Ui)
//line transports/webui/views/login.qtpl:38
		qw422016.N().S(`
            `)
//line transports/webui/views/login.qtpl:39
		streamrenderGroup(qw422016, p.Flow.Ui, "default")
//line transports/webui/views/login.qtpl:39
		qw422016.N().S(`
            `)
//line transports/webui/views/login.qtpl:40
		streamrenderGroup(qw422016, p.Flow.Ui, "password")
//line transports/webui/views/login.qtpl:40
		qw422016.N().S(`
            `)
//line transports/webui/views/login.qtpl:41
		streamrenderSubmit(qw422016, p.Flow.Ui, "password")
//line transports/webui/views/login.qtpl:41
		qw422016.N().S(`
        `)
//line transports/webui/views/login.qtpl:42
		streamformEnd(qw422016)
//line transports/webui/views/login.qtpl:42
		qw422016.N().S(`
    `)
//line transports/webui/views/login.qtpl:43
	} else {
//line transports/webui/views/login.qtpl:43
		qw422016.N().S(`
        <h1 class="text-2xl mt-4 ">Verify login with</h1>
        `)
//line transports/webui/views/login.qtpl:45
		streamformStart(qw422016, p.Flow.Ui)
//line transports/webui/views/login.qtpl:45
		qw422016.N().S(`
            `)
//line transports/webui/views/login.qtpl:46
		streamrenderGroup(qw422016, p.Flow.Ui, "totp")
//line transports/webui/views/login.qtpl:46
		qw422016.N().S(`
            `)
//line transports/webui/views/login.qtpl:47
		streamrenderSubmit(qw422016, p.Flow.Ui, "totp")
//line transports/webui/views/login.qtpl:47
		qw422016.N().S(`
        `)
//line transports/webui/views/login.qtpl:48
		streamformEnd(qw422016)
//line transports/webui/views/login.qtpl:48
		qw422016.N().S(`
    `)
//line transports/webui/views/login.qtpl:49
	}
//line transports/webui/views/login.qtpl:49
	qw422016.N().S(`
`)
//line transports/webui/views/login.qtpl:50
}

//line transports/webui/views/login.qtpl:50
func (p LoginPage) WriteBody(qq422016 qtio422016.Writer) {
//line transports/webui/views/login.qtpl:50
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transports/webui/views/login.qtpl:50
	p.StreamBody(qw422016)
//line transports/webui/views/login.qtpl:50
	qt422016.ReleaseWriter(qw422016)
//line transports/webui/views/login.qtpl:50
}

//line transports/webui/views/login.qtpl:50
func (p LoginPage) Body() string {
//line transports/webui/views/login.qtpl:50
	qb422016 := qt422016.AcquireByteBuffer()
//line transports/webui/views/login.qtpl:50
	p.WriteBody(qb422016)
//line transports/webui/views/login.qtpl:50
	qs422016 := string(qb422016.B)
//line transports/webui/views/login.qtpl:50
	qt422016.ReleaseByteBuffer(qb422016)
//line transports/webui/views/login.qtpl:50
	return qs422016
//line transports/webui/views/login.qtpl:50
}
