// Code generated by qtc from "login.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line transports/webui/views/login.qtpl:1
package views

//line transports/webui/views/login.qtpl:1
import ory "github.com/ory/client-go"

//line transports/webui/views/login.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line transports/webui/views/login.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line transports/webui/views/login.qtpl:2
type Page interface {
//line transports/webui/views/login.qtpl:2
	Body() string
//line transports/webui/views/login.qtpl:2
	StreamBody(qw422016 *qt422016.Writer)
//line transports/webui/views/login.qtpl:2
	WriteBody(qq422016 qtio422016.Writer)
//line transports/webui/views/login.qtpl:2
}

//line transports/webui/views/login.qtpl:6
func StreamLayout(qw422016 *qt422016.Writer, p Page) {
//line transports/webui/views/login.qtpl:6
	qw422016.N().S(`

<!DOCTYPE html>
<html lang="en" class="bg-[#f8fafc]">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="`)
//line transports/webui/views/login.qtpl:14
	qw422016.E().S(U("/static/style.css"))
//line transports/webui/views/login.qtpl:14
	qw422016.N().S(`" />
    </head>
    <body>
        `)
//line transports/webui/views/login.qtpl:17
	p.StreamBody(qw422016)
//line transports/webui/views/login.qtpl:17
	qw422016.N().S(`
    </body>
</html>

`)
//line transports/webui/views/login.qtpl:21
}

//line transports/webui/views/login.qtpl:21
func WriteLayout(qq422016 qtio422016.Writer, p Page) {
//line transports/webui/views/login.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transports/webui/views/login.qtpl:21
	StreamLayout(qw422016, p)
//line transports/webui/views/login.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line transports/webui/views/login.qtpl:21
}

//line transports/webui/views/login.qtpl:21
func Layout(p Page) string {
//line transports/webui/views/login.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
//line transports/webui/views/login.qtpl:21
	WriteLayout(qb422016, p)
//line transports/webui/views/login.qtpl:21
	qs422016 := string(qb422016.B)
//line transports/webui/views/login.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
//line transports/webui/views/login.qtpl:21
	return qs422016
//line transports/webui/views/login.qtpl:21
}

//line transports/webui/views/login.qtpl:24
type LoginPage struct {
	Flow *ory.LoginFlow
}

//line transports/webui/views/login.qtpl:28
func (p LoginPage) StreamBody(qw422016 *qt422016.Writer) {
//line transports/webui/views/login.qtpl:28
	qw422016.N().S(`
    <main class="mt-12 mx-auto w-full md:max-w-[420px] bg-white rounded-md overflow-hidden">
        <header class="bg-secondary-500 h-14 py-3">
            <img src="`)
//line transports/webui/views/login.qtpl:31
	qw422016.E().S(U("/static/logo-white.png"))
//line transports/webui/views/login.qtpl:31
	qw422016.N().S(`" alt="SensorBucket Logo" class="h-full mx-auto" />
        </header>
        <section class="px-6 mb-4 space-y-2">
            <h1 class="text-2xl mt-4 ">Login</h1>
            `)
//line transports/webui/views/login.qtpl:35
	streamrenderGroup(qw422016, p.Flow.Ui, "password")
//line transports/webui/views/login.qtpl:35
	qw422016.N().S(`
            <a
                href="`)
//line transports/webui/views/login.qtpl:37
	qw422016.E().S(U("/auth/recovery"))
//line transports/webui/views/login.qtpl:37
	qw422016.N().S(`"
                class="block text-center"
            >Forgot your password?</a>
        </section>
    </main>
`)
//line transports/webui/views/login.qtpl:42
}

//line transports/webui/views/login.qtpl:42
func (p LoginPage) WriteBody(qq422016 qtio422016.Writer) {
//line transports/webui/views/login.qtpl:42
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transports/webui/views/login.qtpl:42
	p.StreamBody(qw422016)
//line transports/webui/views/login.qtpl:42
	qt422016.ReleaseWriter(qw422016)
//line transports/webui/views/login.qtpl:42
}

//line transports/webui/views/login.qtpl:42
func (p LoginPage) Body() string {
//line transports/webui/views/login.qtpl:42
	qb422016 := qt422016.AcquireByteBuffer()
//line transports/webui/views/login.qtpl:42
	p.WriteBody(qb422016)
//line transports/webui/views/login.qtpl:42
	qs422016 := string(qb422016.B)
//line transports/webui/views/login.qtpl:42
	qt422016.ReleaseByteBuffer(qb422016)
//line transports/webui/views/login.qtpl:42
	return qs422016
//line transports/webui/views/login.qtpl:42
}
