// Code generated by qtc from "tenantSwitchPage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line transports/webui/views/tenantSwitchPage.qtpl:1
package views

//line transports/webui/views/tenantSwitchPage.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line transports/webui/views/tenantSwitchPage.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line transports/webui/views/tenantSwitchPage.qtpl:2
type TenantSwitchingPage struct {
	Base
	Tenants []TenantView
}

type TenantView struct {
	ID       int64
	Name     string
	ImageURL string
}

//line transports/webui/views/tenantSwitchPage.qtpl:14
func (p *TenantSwitchingPage) StreamBody(qw422016 *qt422016.Writer) {
//line transports/webui/views/tenantSwitchPage.qtpl:14
	qw422016.N().S(`
    <h1 class="text-center text-xl mt-4">Switch to tenant</h1>
    `)
//line transports/webui/views/tenantSwitchPage.qtpl:16
	p.streamrenderTenantList(qw422016)
//line transports/webui/views/tenantSwitchPage.qtpl:16
	qw422016.N().S(`
`)
//line transports/webui/views/tenantSwitchPage.qtpl:17
}

//line transports/webui/views/tenantSwitchPage.qtpl:17
func (p *TenantSwitchingPage) WriteBody(qq422016 qtio422016.Writer) {
//line transports/webui/views/tenantSwitchPage.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transports/webui/views/tenantSwitchPage.qtpl:17
	p.StreamBody(qw422016)
//line transports/webui/views/tenantSwitchPage.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line transports/webui/views/tenantSwitchPage.qtpl:17
}

//line transports/webui/views/tenantSwitchPage.qtpl:17
func (p *TenantSwitchingPage) Body() string {
//line transports/webui/views/tenantSwitchPage.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line transports/webui/views/tenantSwitchPage.qtpl:17
	p.WriteBody(qb422016)
//line transports/webui/views/tenantSwitchPage.qtpl:17
	qs422016 := string(qb422016.B)
//line transports/webui/views/tenantSwitchPage.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line transports/webui/views/tenantSwitchPage.qtpl:17
	return qs422016
//line transports/webui/views/tenantSwitchPage.qtpl:17
}

//line transports/webui/views/tenantSwitchPage.qtpl:19
func (p *TenantSwitchingPage) streamrenderTenantList(qw422016 *qt422016.Writer) {
//line transports/webui/views/tenantSwitchPage.qtpl:19
	qw422016.N().S(`
    <ul class="flex flex-col max-h-[50vh] overflow-y-auto">
        `)
//line transports/webui/views/tenantSwitchPage.qtpl:21
	for _, tenant := range p.Tenants {
//line transports/webui/views/tenantSwitchPage.qtpl:21
		qw422016.N().S(`
            `)
//line transports/webui/views/tenantSwitchPage.qtpl:22
		streamrenderTenantListEntry(qw422016, tenant)
//line transports/webui/views/tenantSwitchPage.qtpl:22
		qw422016.N().S(`
        `)
//line transports/webui/views/tenantSwitchPage.qtpl:23
	}
//line transports/webui/views/tenantSwitchPage.qtpl:23
	qw422016.N().S(`
    </ul>
`)
//line transports/webui/views/tenantSwitchPage.qtpl:25
}

//line transports/webui/views/tenantSwitchPage.qtpl:25
func (p *TenantSwitchingPage) writerenderTenantList(qq422016 qtio422016.Writer) {
//line transports/webui/views/tenantSwitchPage.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transports/webui/views/tenantSwitchPage.qtpl:25
	p.streamrenderTenantList(qw422016)
//line transports/webui/views/tenantSwitchPage.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line transports/webui/views/tenantSwitchPage.qtpl:25
}

//line transports/webui/views/tenantSwitchPage.qtpl:25
func (p *TenantSwitchingPage) renderTenantList() string {
//line transports/webui/views/tenantSwitchPage.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line transports/webui/views/tenantSwitchPage.qtpl:25
	p.writerenderTenantList(qb422016)
//line transports/webui/views/tenantSwitchPage.qtpl:25
	qs422016 := string(qb422016.B)
//line transports/webui/views/tenantSwitchPage.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line transports/webui/views/tenantSwitchPage.qtpl:25
	return qs422016
//line transports/webui/views/tenantSwitchPage.qtpl:25
}

//line transports/webui/views/tenantSwitchPage.qtpl:27
func streamrenderTenantListEntry(qw422016 *qt422016.Writer, t TenantView) {
//line transports/webui/views/tenantSwitchPage.qtpl:27
	qw422016.N().S(`
    <li>
        <a class="px-2 py-6 flex align-baseline gap-6 hover:bg-gray-50" href="#">
            <div class="w-1/3">
            <img src=`)
//line transports/webui/views/tenantSwitchPage.qtpl:31
	qw422016.E().S(t.ImageURL)
//line transports/webui/views/tenantSwitchPage.qtpl:31
	qw422016.N().S(`>
            </div>
            <div class="w-2/3">
                <h3 class="text-lg">`)
//line transports/webui/views/tenantSwitchPage.qtpl:34
	qw422016.E().S(t.Name)
//line transports/webui/views/tenantSwitchPage.qtpl:34
	qw422016.N().S(`</h3>
            </div>
        </a>
    </li>
`)
//line transports/webui/views/tenantSwitchPage.qtpl:38
}

//line transports/webui/views/tenantSwitchPage.qtpl:38
func writerenderTenantListEntry(qq422016 qtio422016.Writer, t TenantView) {
//line transports/webui/views/tenantSwitchPage.qtpl:38
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transports/webui/views/tenantSwitchPage.qtpl:38
	streamrenderTenantListEntry(qw422016, t)
//line transports/webui/views/tenantSwitchPage.qtpl:38
	qt422016.ReleaseWriter(qw422016)
//line transports/webui/views/tenantSwitchPage.qtpl:38
}

//line transports/webui/views/tenantSwitchPage.qtpl:38
func renderTenantListEntry(t TenantView) string {
//line transports/webui/views/tenantSwitchPage.qtpl:38
	qb422016 := qt422016.AcquireByteBuffer()
//line transports/webui/views/tenantSwitchPage.qtpl:38
	writerenderTenantListEntry(qb422016, t)
//line transports/webui/views/tenantSwitchPage.qtpl:38
	qs422016 := string(qb422016.B)
//line transports/webui/views/tenantSwitchPage.qtpl:38
	qt422016.ReleaseByteBuffer(qb422016)
//line transports/webui/views/tenantSwitchPage.qtpl:38
	return qs422016
//line transports/webui/views/tenantSwitchPage.qtpl:38
}
