// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package measurements_test

import (
	"github.com/google/uuid"
	"sensorbucket.nl/sensorbucket/internal/pagination"
	"sensorbucket.nl/sensorbucket/services/core/measurements"
	"sync"
)

// Ensure, that StoreMock does implement measurements.Store.
// If this is not the case, regenerate this file with moq.
var _ measurements.Store = &StoreMock{}

// StoreMock is a mock implementation of measurements.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked measurements.Store
//		mockedStore := &StoreMock{
//			CreateDatastreamFunc: func(datastream *measurements.Datastream) error {
//				panic("mock out the CreateDatastream method")
//			},
//			FindDatastreamFunc: func(sensorID int64, observedProperty string) (*measurements.Datastream, error) {
//				panic("mock out the FindDatastream method")
//			},
//			GetDatastreamFunc: func(id uuid.UUID, filter measurements.DatastreamFilter) (*measurements.Datastream, error) {
//				panic("mock out the GetDatastream method")
//			},
//			InsertFunc: func(measurement measurements.Measurement) error {
//				panic("mock out the Insert method")
//			},
//			ListDatastreamsFunc: func(datastreamFilter measurements.DatastreamFilter, request pagination.Request) (*pagination.Page[measurements.Datastream], error) {
//				panic("mock out the ListDatastreams method")
//			},
//			QueryFunc: func(filter measurements.Filter, request pagination.Request) (*pagination.Page[measurements.Measurement], error) {
//				panic("mock out the Query method")
//			},
//		}
//
//		// use mockedStore in code that requires measurements.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// CreateDatastreamFunc mocks the CreateDatastream method.
	CreateDatastreamFunc func(datastream *measurements.Datastream) error

	// FindDatastreamFunc mocks the FindDatastream method.
	FindDatastreamFunc func(sensorID int64, observedProperty string) (*measurements.Datastream, error)

	// GetDatastreamFunc mocks the GetDatastream method.
	GetDatastreamFunc func(id uuid.UUID, filter measurements.DatastreamFilter) (*measurements.Datastream, error)

	// InsertFunc mocks the Insert method.
	InsertFunc func(measurement measurements.Measurement) error

	// ListDatastreamsFunc mocks the ListDatastreams method.
	ListDatastreamsFunc func(datastreamFilter measurements.DatastreamFilter, request pagination.Request) (*pagination.Page[measurements.Datastream], error)

	// QueryFunc mocks the Query method.
	QueryFunc func(filter measurements.Filter, request pagination.Request) (*pagination.Page[measurements.Measurement], error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateDatastream holds details about calls to the CreateDatastream method.
		CreateDatastream []struct {
			// Datastream is the datastream argument value.
			Datastream *measurements.Datastream
		}
		// FindDatastream holds details about calls to the FindDatastream method.
		FindDatastream []struct {
			// SensorID is the sensorID argument value.
			SensorID int64
			// ObservedProperty is the observedProperty argument value.
			ObservedProperty string
		}
		// GetDatastream holds details about calls to the GetDatastream method.
		GetDatastream []struct {
			// ID is the id argument value.
			ID uuid.UUID
			// Filter is the filter argument value.
			Filter measurements.DatastreamFilter
		}
		// Insert holds details about calls to the Insert method.
		Insert []struct {
			// Measurement is the measurement argument value.
			Measurement measurements.Measurement
		}
		// ListDatastreams holds details about calls to the ListDatastreams method.
		ListDatastreams []struct {
			// DatastreamFilter is the datastreamFilter argument value.
			DatastreamFilter measurements.DatastreamFilter
			// Request is the request argument value.
			Request pagination.Request
		}
		// Query holds details about calls to the Query method.
		Query []struct {
			// Filter is the filter argument value.
			Filter measurements.Filter
			// Request is the request argument value.
			Request pagination.Request
		}
	}
	lockCreateDatastream sync.RWMutex
	lockFindDatastream   sync.RWMutex
	lockGetDatastream    sync.RWMutex
	lockInsert           sync.RWMutex
	lockListDatastreams  sync.RWMutex
	lockQuery            sync.RWMutex
}

// CreateDatastream calls CreateDatastreamFunc.
func (mock *StoreMock) CreateDatastream(datastream *measurements.Datastream) error {
	if mock.CreateDatastreamFunc == nil {
		panic("StoreMock.CreateDatastreamFunc: method is nil but Store.CreateDatastream was just called")
	}
	callInfo := struct {
		Datastream *measurements.Datastream
	}{
		Datastream: datastream,
	}
	mock.lockCreateDatastream.Lock()
	mock.calls.CreateDatastream = append(mock.calls.CreateDatastream, callInfo)
	mock.lockCreateDatastream.Unlock()
	return mock.CreateDatastreamFunc(datastream)
}

// CreateDatastreamCalls gets all the calls that were made to CreateDatastream.
// Check the length with:
//
//	len(mockedStore.CreateDatastreamCalls())
func (mock *StoreMock) CreateDatastreamCalls() []struct {
	Datastream *measurements.Datastream
} {
	var calls []struct {
		Datastream *measurements.Datastream
	}
	mock.lockCreateDatastream.RLock()
	calls = mock.calls.CreateDatastream
	mock.lockCreateDatastream.RUnlock()
	return calls
}

// FindDatastream calls FindDatastreamFunc.
func (mock *StoreMock) FindDatastream(sensorID int64, observedProperty string) (*measurements.Datastream, error) {
	if mock.FindDatastreamFunc == nil {
		panic("StoreMock.FindDatastreamFunc: method is nil but Store.FindDatastream was just called")
	}
	callInfo := struct {
		SensorID         int64
		ObservedProperty string
	}{
		SensorID:         sensorID,
		ObservedProperty: observedProperty,
	}
	mock.lockFindDatastream.Lock()
	mock.calls.FindDatastream = append(mock.calls.FindDatastream, callInfo)
	mock.lockFindDatastream.Unlock()
	return mock.FindDatastreamFunc(sensorID, observedProperty)
}

// FindDatastreamCalls gets all the calls that were made to FindDatastream.
// Check the length with:
//
//	len(mockedStore.FindDatastreamCalls())
func (mock *StoreMock) FindDatastreamCalls() []struct {
	SensorID         int64
	ObservedProperty string
} {
	var calls []struct {
		SensorID         int64
		ObservedProperty string
	}
	mock.lockFindDatastream.RLock()
	calls = mock.calls.FindDatastream
	mock.lockFindDatastream.RUnlock()
	return calls
}

// GetDatastream calls GetDatastreamFunc.
func (mock *StoreMock) GetDatastream(id uuid.UUID, filter measurements.DatastreamFilter) (*measurements.Datastream, error) {
	if mock.GetDatastreamFunc == nil {
		panic("StoreMock.GetDatastreamFunc: method is nil but Store.GetDatastream was just called")
	}
	callInfo := struct {
		ID     uuid.UUID
		Filter measurements.DatastreamFilter
	}{
		ID:     id,
		Filter: filter,
	}
	mock.lockGetDatastream.Lock()
	mock.calls.GetDatastream = append(mock.calls.GetDatastream, callInfo)
	mock.lockGetDatastream.Unlock()
	return mock.GetDatastreamFunc(id, filter)
}

// GetDatastreamCalls gets all the calls that were made to GetDatastream.
// Check the length with:
//
//	len(mockedStore.GetDatastreamCalls())
func (mock *StoreMock) GetDatastreamCalls() []struct {
	ID     uuid.UUID
	Filter measurements.DatastreamFilter
} {
	var calls []struct {
		ID     uuid.UUID
		Filter measurements.DatastreamFilter
	}
	mock.lockGetDatastream.RLock()
	calls = mock.calls.GetDatastream
	mock.lockGetDatastream.RUnlock()
	return calls
}

// Insert calls InsertFunc.
func (mock *StoreMock) Insert(measurement measurements.Measurement) error {
	if mock.InsertFunc == nil {
		panic("StoreMock.InsertFunc: method is nil but Store.Insert was just called")
	}
	callInfo := struct {
		Measurement measurements.Measurement
	}{
		Measurement: measurement,
	}
	mock.lockInsert.Lock()
	mock.calls.Insert = append(mock.calls.Insert, callInfo)
	mock.lockInsert.Unlock()
	return mock.InsertFunc(measurement)
}

// InsertCalls gets all the calls that were made to Insert.
// Check the length with:
//
//	len(mockedStore.InsertCalls())
func (mock *StoreMock) InsertCalls() []struct {
	Measurement measurements.Measurement
} {
	var calls []struct {
		Measurement measurements.Measurement
	}
	mock.lockInsert.RLock()
	calls = mock.calls.Insert
	mock.lockInsert.RUnlock()
	return calls
}

// ListDatastreams calls ListDatastreamsFunc.
func (mock *StoreMock) ListDatastreams(datastreamFilter measurements.DatastreamFilter, request pagination.Request) (*pagination.Page[measurements.Datastream], error) {
	if mock.ListDatastreamsFunc == nil {
		panic("StoreMock.ListDatastreamsFunc: method is nil but Store.ListDatastreams was just called")
	}
	callInfo := struct {
		DatastreamFilter measurements.DatastreamFilter
		Request          pagination.Request
	}{
		DatastreamFilter: datastreamFilter,
		Request:          request,
	}
	mock.lockListDatastreams.Lock()
	mock.calls.ListDatastreams = append(mock.calls.ListDatastreams, callInfo)
	mock.lockListDatastreams.Unlock()
	return mock.ListDatastreamsFunc(datastreamFilter, request)
}

// ListDatastreamsCalls gets all the calls that were made to ListDatastreams.
// Check the length with:
//
//	len(mockedStore.ListDatastreamsCalls())
func (mock *StoreMock) ListDatastreamsCalls() []struct {
	DatastreamFilter measurements.DatastreamFilter
	Request          pagination.Request
} {
	var calls []struct {
		DatastreamFilter measurements.DatastreamFilter
		Request          pagination.Request
	}
	mock.lockListDatastreams.RLock()
	calls = mock.calls.ListDatastreams
	mock.lockListDatastreams.RUnlock()
	return calls
}

// Query calls QueryFunc.
func (mock *StoreMock) Query(filter measurements.Filter, request pagination.Request) (*pagination.Page[measurements.Measurement], error) {
	if mock.QueryFunc == nil {
		panic("StoreMock.QueryFunc: method is nil but Store.Query was just called")
	}
	callInfo := struct {
		Filter  measurements.Filter
		Request pagination.Request
	}{
		Filter:  filter,
		Request: request,
	}
	mock.lockQuery.Lock()
	mock.calls.Query = append(mock.calls.Query, callInfo)
	mock.lockQuery.Unlock()
	return mock.QueryFunc(filter, request)
}

// QueryCalls gets all the calls that were made to Query.
// Check the length with:
//
//	len(mockedStore.QueryCalls())
func (mock *StoreMock) QueryCalls() []struct {
	Filter  measurements.Filter
	Request pagination.Request
} {
	var calls []struct {
		Filter  measurements.Filter
		Request pagination.Request
	}
	mock.lockQuery.RLock()
	calls = mock.calls.Query
	mock.lockQuery.RUnlock()
	return calls
}

// Ensure, that DatastreamFinderCreaterMock does implement measurements.DatastreamFinderCreater.
// If this is not the case, regenerate this file with moq.
var _ measurements.DatastreamFinderCreater = &DatastreamFinderCreaterMock{}

// DatastreamFinderCreaterMock is a mock implementation of measurements.DatastreamFinderCreater.
//
//	func TestSomethingThatUsesDatastreamFinderCreater(t *testing.T) {
//
//		// make and configure a mocked measurements.DatastreamFinderCreater
//		mockedDatastreamFinderCreater := &DatastreamFinderCreaterMock{
//			CreateDatastreamFunc: func(datastream *measurements.Datastream) error {
//				panic("mock out the CreateDatastream method")
//			},
//			FindDatastreamFunc: func(sensorID int64, observedProperty string) (*measurements.Datastream, error) {
//				panic("mock out the FindDatastream method")
//			},
//		}
//
//		// use mockedDatastreamFinderCreater in code that requires measurements.DatastreamFinderCreater
//		// and then make assertions.
//
//	}
type DatastreamFinderCreaterMock struct {
	// CreateDatastreamFunc mocks the CreateDatastream method.
	CreateDatastreamFunc func(datastream *measurements.Datastream) error

	// FindDatastreamFunc mocks the FindDatastream method.
	FindDatastreamFunc func(sensorID int64, observedProperty string) (*measurements.Datastream, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateDatastream holds details about calls to the CreateDatastream method.
		CreateDatastream []struct {
			// Datastream is the datastream argument value.
			Datastream *measurements.Datastream
		}
		// FindDatastream holds details about calls to the FindDatastream method.
		FindDatastream []struct {
			// SensorID is the sensorID argument value.
			SensorID int64
			// ObservedProperty is the observedProperty argument value.
			ObservedProperty string
		}
	}
	lockCreateDatastream sync.RWMutex
	lockFindDatastream   sync.RWMutex
}

// CreateDatastream calls CreateDatastreamFunc.
func (mock *DatastreamFinderCreaterMock) CreateDatastream(datastream *measurements.Datastream) error {
	if mock.CreateDatastreamFunc == nil {
		panic("DatastreamFinderCreaterMock.CreateDatastreamFunc: method is nil but DatastreamFinderCreater.CreateDatastream was just called")
	}
	callInfo := struct {
		Datastream *measurements.Datastream
	}{
		Datastream: datastream,
	}
	mock.lockCreateDatastream.Lock()
	mock.calls.CreateDatastream = append(mock.calls.CreateDatastream, callInfo)
	mock.lockCreateDatastream.Unlock()
	return mock.CreateDatastreamFunc(datastream)
}

// CreateDatastreamCalls gets all the calls that were made to CreateDatastream.
// Check the length with:
//
//	len(mockedDatastreamFinderCreater.CreateDatastreamCalls())
func (mock *DatastreamFinderCreaterMock) CreateDatastreamCalls() []struct {
	Datastream *measurements.Datastream
} {
	var calls []struct {
		Datastream *measurements.Datastream
	}
	mock.lockCreateDatastream.RLock()
	calls = mock.calls.CreateDatastream
	mock.lockCreateDatastream.RUnlock()
	return calls
}

// FindDatastream calls FindDatastreamFunc.
func (mock *DatastreamFinderCreaterMock) FindDatastream(sensorID int64, observedProperty string) (*measurements.Datastream, error) {
	if mock.FindDatastreamFunc == nil {
		panic("DatastreamFinderCreaterMock.FindDatastreamFunc: method is nil but DatastreamFinderCreater.FindDatastream was just called")
	}
	callInfo := struct {
		SensorID         int64
		ObservedProperty string
	}{
		SensorID:         sensorID,
		ObservedProperty: observedProperty,
	}
	mock.lockFindDatastream.Lock()
	mock.calls.FindDatastream = append(mock.calls.FindDatastream, callInfo)
	mock.lockFindDatastream.Unlock()
	return mock.FindDatastreamFunc(sensorID, observedProperty)
}

// FindDatastreamCalls gets all the calls that were made to FindDatastream.
// Check the length with:
//
//	len(mockedDatastreamFinderCreater.FindDatastreamCalls())
func (mock *DatastreamFinderCreaterMock) FindDatastreamCalls() []struct {
	SensorID         int64
	ObservedProperty string
} {
	var calls []struct {
		SensorID         int64
		ObservedProperty string
	}
	mock.lockFindDatastream.RLock()
	calls = mock.calls.FindDatastream
	mock.lockFindDatastream.RUnlock()
	return calls
}
