get:
  x-is-paginated: true
  operationId: ListIngresses
  summary: List ingresses
  description: |
    Lists ingresses that match the provided filter.
  tags: [Tracing]
  parameters:
    - in: query
      name: cursor
      description: The cursor for the current page
      schema:
        type: string
    - in: query
      name: limit
      description: |
        The maximum amount of items per page. Not applicable if `cursor` parameter is given. System limits are in place.
      schema:
        type: integer
    - in: query
      name: tracing_id
      style: form
      explode: true
      schema:
        type: array
        items:
          type: string
          format: uuid
          example: "a59d28c8-2a0f-4e89-9f49-6942f1c04342"
  responses:
    "200":
      description: Fetched ingresses
      content:
        application/json:
          schema:
            allOf:
              - $ref: "./schemas.yaml#/paginatedResponse"
              - type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "schemas.yaml#/archivedIngress"
    "400":
      $ref: "./responses.yaml#/400"
    "401":
      $ref: "./responses.yaml#/401"
    "403":
      $ref: "./responses.yaml#/403"
