paginatedResponse:
  type: object
  required:
    - links
    - page_size
    - total_count
    - data
  properties:
    links:
      type: object
      properties:
        previous:
          type: string
        next:
          type: string
    page_size:
      type: integer
    total_count:
      type: integer
    data:
      type: array
      items: {}
        
createDeviceRequest:
  type: object
  required:
    - code
  properties:
    code:
      type: string
      example: mfm1000
    description:
      type: string
      example: Grasfield pipe 24
#    organisation:
#      type: string
#      example: provincie_zeeland
    latitude:
      type: number
      format: double
      example: 1.2345
    longitude:
      type: number
      format: double
      example: 1.2345
    location_description:
      type: string
      example: "Description of location"
    properties:
      type: object
      example:
        eui: "060708090A0B0C0D"

updateDeviceRequest:
    type: object
    properties:
      description:
        type: integer
        example: 1
      latitude:
        type: number
        format: double
        example: 1.2345
      longitude:
        type: number
        format: double
        example: 1.2345
      location_description:
        type: string
        example: "Description of location"
      properties:
        type: object
        example:
          eui: "060708090A0B0C0D"

device:
  type: object
  required:
    - id
    - code
    - state
    - description
    - organisation
    - properties
    - sensors
    - created_at
  properties:
    id:
      type: integer
      format: int64
      example: 1
    code:
      type: string
      example: mfm1000
    state:
      type: integer
    description:
      type: string
      example: Grasfield pipe 24
    organisation:
      type: string
      example: provincie_zeeland
    properties:
      type: object
      example:
        eui: "060708090A0B0C0D"
    altitude:
      type: number
      format: double
      example: 1.2345
    latitude:
      type: number
      format: double
      example: 1.2345
    longitude:
      type: number
      format: double
      example: 1.2345
    location_description:
      type: string
      example: "Description of location"
    sensors:
      type: array
      items:
        $ref: '#/sensor'
    created_at:
      type: string
      format: date-time

createSensorRequest:
  type: object
  required:
    - code
    - external_id
  properties:
    code:
      type: string
      example: S123
    description:
      type: string
      example: Pressure sensor at 5 meters depth
    external_id:
      type: string
      example: "5"
    brand:
      type: string
      example: "sensor brand ABC"
    properties:
      type: object
      example: 
        mount_height: 15cm
    archive_time:
      type: integer
      example: 7

sensor:
  type: object
  required:
    - id
    - code
    - description
    - external_id
    - brand
    - properties
    - created_at
    - device_id
  properties:
    id:
      type: integer
      format: int64
      example: 1
    device_id:
      type: integer
      format: int64
      example: 1
    code:
      type: string
      example: S123
    description:
      type: string
      example: Pressure sensor at 5 meters depth
    external_id:
      type: string
      example: "5"
    brand:
      type: string
      example: "SensorCompany LTD. SCL115"
    archive_time:
      type: integer
      example: 7
    properties:
      type: object
      example: 
        mount_height: 15cm
    created_at:
      type: string
      format: date-time
      example: 2023-05-17T15:00:00Z

tenant:
  type: object
  required:
    - id
    - name
    - address
    - zip_code
    - city
  properties:
    id:
      type: integer
      format: int64
      example: 1
    name:
      type: string
      example: Provincie Zeeland
    address:
      type: string
      example: Zeeland
    zip_code:
      type: string
      example: 4331 ZE
    city:
      type: string
      example: Vlissingen
    chamber_of_commerce_id:
      type: string
    headquarter_id:
      type: string
    

apiKey:
  type: object
  required:
    - id
    - name
    - tenant_id
    - tenant_name
    - created
  properties:
    id:
      type: integer
      format: int64
      example: 1
    name:
      type: string
      example: Provincie Zeeland
    tenant_id:
      type: integer
      format: int64
      example: 19
    tenant_name:
      type: string
      example: Provincie Zeeland
    expiration_date:
      type: string
      format: date-time
      example: 2023-05-17T15:00:00Z
    created:
      type: string
      format: date-time
      example: 2022-05-17T15:00:00Z

createApiKeyRequest:
  type: object
  required:
    - name
    - tenant_id
  properties:
    name:
      type: string
      example: Device Beheerder
    tenant_id:
      type: integer
      format: int64
      example: 19
    expiration_date:
      type: string
      format: date-time
      example: 2023-05-17T15:00:00Z

apiKeyCreated:
  type: object
  required:
    - api_key
  properties:
    api_key:
      type: string
      example: MjU5MzE1NDgwMjE2NTMwMTEyODo2MjY2MDdkMGViY2Q5MGRhMTRkZWE4NGY4MjEzYjRiNw

trace:
  type: object
  required:
    - tracing_id
    - device_id
    - start_time
    - steps
    - status
    - status_string
  properties:
    tracing_id:
      type: string
      example: "a59d28c8-2a0f-4e89-9f49-6942f1c04342"
    device_id:
      type: integer
      format: int64
      example: 37
      description: id is 0 if not defined
    start_time:
      type: string
      format: date-time
    status:
      type: integer
      example: 2
    status_string:
      type: string
      example: "succes"
    steps:
      type: array
      items:
        $ref: '#/trace_step'

trace_step:
  type: object
  required:
    - status
    - status_string
    - duration
    - error
  properties:
    start_time:
      type: string
      format: date-time
    status:
      type: integer
      example: 2
    status_string:
      type: string
      example: "succes"
    duration:
      type: number
      format: double
      description: Duration in seconds
      example: 5.321
    error:
      type: string

measurement:
  type: object
  required:
    - uplink_message_id
    - device_id
    - device_code
    - device_state
    - sensor_id
    - sensor_code
    - sensor_external_id
    - datastream_id
    - datastream_observed_property
    - datastream_unit_of_measurement
    - measurement_timestamp
    - measurement_value
    - measurement_expiration
  properties:
    uplink_message_id:
      type: string
      example: ca29e28e-eeb6-4662-922c-6cf6a36ccb6e
    device_id:
      type: integer
      format: int64
      example: 5
    device_code:
      type: string
      example: mfm1000
    device_description:
      type: string
      example: Particulate matter device
    device_latitude:
      type: number
      format: double
      example: 5.131313
    device_longitude:
      type: number
      format: double
      example: 5.131313
    device_altitude:
      type: number
      format: double
      example: 5.131313
    device_location_description:
      type: string
      example: Grasfield pipe 24
    device_properties:
      type: object
      example:
        eui: "060708090A0B0C0D"
    device_state:
      type: integer
      example: 0
    sensor_id:
      type: integer
      format: int64
      example: 3 
    sensor_code:
      type: string
      example: S123
    sensor_description:
      type: string
      example: Pressure sensor at 5 meters depth
    sensor_external_id:
      type: string
      example: "5"
    sensor_properties:
      type: object
      example: {}
    sensor_brand:
      type: string
      example: "SensorCompany Inc. SC123" 
    sensor_archive_time:
      type: integer
      example: 7 
    datastream_id:
      type: string
      format: uuid
      example: 153205d7-bdfc-4a0b-9de5-c6fa04c665f6
    datastream_description:
      type: string
      example: "Concentration of particles smaller than 2.5 micrometer" 
    datastream_observed_property:
      type: string
      example: "pm2.5" 
    datastream_unit_of_measurement:
      type: string
      example: "ug/cm3"
    measurement_timestamp:
      type: string
      format: date-time
      example: "2022-01-01T00:00:00Z"
    measurement_value:
      type: number
      format: double
      example: 3.44
    measurement_latitude:
      type: number
      format: double
      example: 3.44
    measurement_longitude:
      type: number
      format: double
      example: 3.44
    measurement_altitude:
      type: number
      format: double
      example: 3.44
    measurement_properties:
      type: object
    measurement_expiration:
      type: string
      format: date-time
      example: "2022-01-01T00:00:00Z"
    created_at:
      type: string
      format: date-time
      example: 2022-01-01T00:00:00Z

pipeline:
  type: object
  required:
    - id
    - description
    - steps
    - status
    - last_status_change
  properties:
    id:
      type: string
      example: 9d4a0944-c11d-42ef-880f-a97c9619c5c0
    description:
      type: string
      example: Pipeline for Multiflexmeter Groundwater devices
    steps:
      type: array
      items:
        type: string
      example:
        - "TTN@1.0.0"
        - "MFMGroundwater@1.0.0"
    status:
      type: string
      description: either active or inactive
      example: active
    last_status_change:
      type: string
      format: date-time
      example: 2022-01-01T00:00:00Z
    created_at:
      type: string
      format: date-time
      example: 2022-01-01T00:00:00Z


createPipelineRequest:
  type: object
  properties:
    description:
      type: string
      example: Pipeline for Multiflexmeter Groundwater devices
    steps:
      type: array
      items:
        type: string
      example:
        - "TTN@1.0.0"
        - "MFMGroundwater@1.0.0"

updatePipelineRequest:
  type: object
  properties:
    description:
      type: string
      example: Pipeline for Multiflexmeter Groundwater devices
    steps:
      type: array
      items:
        type: string
      example:
        - "TTN@1.0.0"
        - "MFMGroundwater@1.0.0"
    status:
      type: string
      description: |
        Used to change a pipeline from inactive to active or vice-versa. 
        Moving from active to inactive can also be achieve by `DELETE`ing the pipeline resource.
      example: active

datastream:
  type: object
  required:
    - id
    - description
    - sensor_id
    - observed_property
    - unit_of_measurement
    - created_at
  properties:
    id:
      type: string
      format: uuid
    description:
      type: string
    sensor_id:
      type: integer
    observed_property:
      type: string
    unit_of_measurement:
      type: string
      format: ucum
    created_at:
      type: string
      #format: date-time
      example: "2022-01-01T00:00:00Z"

sensorGroup:
  type: object
  required:
    - id
    - name
    - description
    - sensors
  properties:
    id:
      type: integer
      format: int64
    name:
      type: string
    description:
      type: string
    sensors:
      type: array
      items:
        type: integer
        format: int64
createSensorGroupRequest:
  type: object
  properties:
    name:
      type: string
    description:
      type: string
updateSensorGroupRequest:
  type: object
  properties:
    name:
      type: string
    description:
      type: string
userWorker:
  type: object
  required:
    - id
    - name
    - description
    - state
    - language
    - organisation
    - revision
    - status
  properties:
    id:
      type: string
      format: uuid
    name:
      type: string
    description:
      type: string
    state:
      type: string
      enum: ["enabled", "disabled"]
    language:
      type: string
      enum: ["python"]
    organisation:
      type: integer
      format: int64
    revision:
      type: integer
    status:
      type: string
      enum: ["unknown", "ready", "error"]
updateWorkerRequest:
  type: object
  properties:
    name:
      type: string
    description:
      type: string
    state:
      type: string
      enum: ["enabled", "disabled"]
    user_code:
      type: string
      format: base64
      description: base64 encoded user code
createUserWorkerRequest:
  type: object
  required:
    - name
    - user_code
  properties:
    name:
      type: string
    description:
      type: string
    user_code:
      type: string
      format: base64
      description: base64 encoded user code
    state:
      type: string
      enum: ["enabled", "disabled"]

ingressDTO:
  type: object
  required:
    - tracing_id
    - pipeline_id
    - owner_id
    - payload
    - created_at
  properties:
    tracing_id:
      type: string
      format: uuid
    pipeline_id:
      type: string
      format: uuid
    owner_id:
      type: integer
      format: int64
    payload:
      type: string
      format: base64
    created_at:
      type: string
      format: date-time

archivedIngress:
  type: object
  required:
    - tracing_id
    - raw_message
    - archived_at
    - expires_at
  properties:
    tracing_id:
      type: string
      format: uuid
    raw_message:
      type: string
      format: base64
    archived_at:
      type: string
      format: date-time
    expires_at:
      type: string
      format: date-time
    ingress_dto:
      $ref: "#/ingressDTO"
