BEGIN;

ALTER TABLE devices ADD COLUMN created_at TIMESTAMPTZ DEFAULT(NOW() AT TIME ZONE 'UTC') NOT NULL;
ALTER TABLE sensors ADD COLUMN created_at TIMESTAMPTZ DEFAULT(NOW() AT TIME ZONE 'UTC') NOT NULL;

COMMIT;
