// Code generated by qtc from "datastream.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line services/dashboard/views/datastream.qtpl:1
package views

//line services/dashboard/views/datastream.qtpl:1
import "sensorbucket.nl/sensorbucket/services/core/devices"

//line services/dashboard/views/datastream.qtpl:2
import "sensorbucket.nl/sensorbucket/services/core/measurements"

//line services/dashboard/views/datastream.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line services/dashboard/views/datastream.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line services/dashboard/views/datastream.qtpl:4
func (p *DatastreamPage) StreamBody(qw422016 *qt422016.Writer) {
//line services/dashboard/views/datastream.qtpl:4
	qw422016.N().S(`
<div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
    <div class="bg-white rounded-md border" id="map">
        <div
            class="w-full h-96"
            hx-ext="leaflet"
            `)
//line services/dashboard/views/datastream.qtpl:10
	if p.Device.Latitude != nil && p.Device.Longitude != nil {
//line services/dashboard/views/datastream.qtpl:10
		qw422016.N().S(`
                data-latitude="`)
//line services/dashboard/views/datastream.qtpl:11
		qw422016.N().F(*p.Device.Latitude)
//line services/dashboard/views/datastream.qtpl:11
		qw422016.N().S(`"
                data-longitude="`)
//line services/dashboard/views/datastream.qtpl:12
		qw422016.N().F(*p.Device.Longitude)
//line services/dashboard/views/datastream.qtpl:12
		qw422016.N().S(`"
                data-zoom="11"
            `)
//line services/dashboard/views/datastream.qtpl:14
	} else {
//line services/dashboard/views/datastream.qtpl:14
		qw422016.N().S(`
                data-latitude="3.943"
                data-longitude="51.573"
                data-zoom="9"
            `)
//line services/dashboard/views/datastream.qtpl:18
	}
//line services/dashboard/views/datastream.qtpl:18
	qw422016.N().S(`
            `)
//line services/dashboard/views/datastream.qtpl:19
	if p.Device.Latitude != nil && p.Device.Longitude != nil {
//line services/dashboard/views/datastream.qtpl:19
		qw422016.N().S(`
                data-markers='[{"lng": `)
//line services/dashboard/views/datastream.qtpl:20
		qw422016.N().F(*p.Device.Longitude)
//line services/dashboard/views/datastream.qtpl:20
		qw422016.N().S(`, "lat": `)
//line services/dashboard/views/datastream.qtpl:20
		qw422016.N().F(*p.Device.Latitude)
//line services/dashboard/views/datastream.qtpl:20
		qw422016.N().S(`}]'
            `)
//line services/dashboard/views/datastream.qtpl:21
	}
//line services/dashboard/views/datastream.qtpl:21
	qw422016.N().S(`
        ></div>
    </div>
    <div class="bg-white rounded-md border" id="device">
        <header class="border-b py-2 px-4 text-sm text-slate-700">
            Device details
        </header>
        <div class="p-4">
            `)
//line services/dashboard/views/datastream.qtpl:29
	StreamDeviceDetailBlock(qw422016, p.Device)
//line services/dashboard/views/datastream.qtpl:29
	qw422016.N().S(`
        </div>
    </div>
    <div class="bg-white rounded-md border" id="sensor">
        <header class="border-b py-2 px-4 text-sm text-slate-700">
            Sensor details
        </header>
        <div class="p-4">
            `)
//line services/dashboard/views/datastream.qtpl:37
	StreamDeviceDetailBlock(qw422016, p.Device)
//line services/dashboard/views/datastream.qtpl:37
	qw422016.N().S(`
        </div>
    </div>
    <div class="bg-white rounded-md border col-span-full" hx-ext="ws" ws-connect="/overview/datastreams/`)
//line services/dashboard/views/datastream.qtpl:40
	qw422016.E().S(p.Datastream.ID.String())
//line services/dashboard/views/datastream.qtpl:40
	qw422016.N().S(`/stream?start=asd">
        <header class="border-b py-2 px-4 text-sm text-slate-700">
            Datastream
        </header>
        <div class="px-4 pt-4 pb-10">
            <div hx-ext="uplot" class="w-full h-80"></div>
        </div>
    </div>
</div>
`)
//line services/dashboard/views/datastream.qtpl:49
}

//line services/dashboard/views/datastream.qtpl:49
func (p *DatastreamPage) WriteBody(qq422016 qtio422016.Writer) {
//line services/dashboard/views/datastream.qtpl:49
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services/dashboard/views/datastream.qtpl:49
	p.StreamBody(qw422016)
//line services/dashboard/views/datastream.qtpl:49
	qt422016.ReleaseWriter(qw422016)
//line services/dashboard/views/datastream.qtpl:49
}

//line services/dashboard/views/datastream.qtpl:49
func (p *DatastreamPage) Body() string {
//line services/dashboard/views/datastream.qtpl:49
	qb422016 := qt422016.AcquireByteBuffer()
//line services/dashboard/views/datastream.qtpl:49
	p.WriteBody(qb422016)
//line services/dashboard/views/datastream.qtpl:49
	qs422016 := string(qb422016.B)
//line services/dashboard/views/datastream.qtpl:49
	qt422016.ReleaseByteBuffer(qb422016)
//line services/dashboard/views/datastream.qtpl:49
	return qs422016
//line services/dashboard/views/datastream.qtpl:49
}

//line services/dashboard/views/datastream.qtpl:52
type DatastreamPage struct {
	BasePage
	Device     devices.Device
	Sensor     devices.Sensor
	Datastream measurements.Datastream
}
