// Code generated by qtc from "detailBlocks.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/detailBlocks.qtpl:1
package views

//line views/detailBlocks.qtpl:1
import "sensorbucket.nl/sensorbucket/pkg/api"

//line views/detailBlocks.qtpl:2
import "sensorbucket.nl/sensorbucket/services/core/devices"

//line views/detailBlocks.qtpl:3
import "fmt"

//line views/detailBlocks.qtpl:4
import "encoding/json"

//line views/detailBlocks.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/detailBlocks.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/detailBlocks.qtpl:6
func StreamDeviceDetailBlock(qw422016 *qt422016.Writer, device api.Device) {
//line views/detailBlocks.qtpl:6
	qw422016.N().S(`
    <div class="grid grid-cols-3 gap-x-8 gap-y-3 [&>*]:min-h-[2rem] text-sm">
        <div class="flex flex-col">
            <small class="text-xs font-semibold text-slate-500">Device Code</small>
            <span>`)
//line views/detailBlocks.qtpl:10
	qw422016.E().S(device.Code)
//line views/detailBlocks.qtpl:10
	qw422016.N().S(`</span>
        </div>
        <div class="flex flex-col">
            <small class="text-xs font-semibold text-slate-500">Device ID</small>
            <span>`)
//line views/detailBlocks.qtpl:14
	qw422016.N().DL(device.Id)
//line views/detailBlocks.qtpl:14
	qw422016.N().S(`</span>
        </div>
        <div class="flex flex-col">
            <small class="text-xs font-semibold text-slate-500">Organisation</small>
            <span>`)
//line views/detailBlocks.qtpl:18
	qw422016.E().S(device.Organisation)
//line views/detailBlocks.qtpl:18
	qw422016.N().S(`</span>
        </div>
        <div class="flex flex-col">
            <small class="text-xs font-semibold text-slate-500">Sensor Count</small>
            <span>`)
//line views/detailBlocks.qtpl:22
	qw422016.E().S(fmt.Sprintf("Has %d sensors", len(device.Sensors)))
//line views/detailBlocks.qtpl:22
	qw422016.N().S(`</span>
        </div>
        <div class="flex flex-col">
            <small class="text-xs font-semibold text-slate-500">State</small>
            <span>
            `)
//line views/detailBlocks.qtpl:27
	switch devices.DeviceState(device.State) {
//line views/detailBlocks.qtpl:28
	case devices.DeviceStateUnknown:
//line views/detailBlocks.qtpl:28
		qw422016.N().S(`
            Unknown
            `)
//line views/detailBlocks.qtpl:30
	case devices.DeviceEnabled:
//line views/detailBlocks.qtpl:30
		qw422016.N().S(`
            Enabled
            `)
//line views/detailBlocks.qtpl:32
	case devices.DeviceDisabled:
//line views/detailBlocks.qtpl:32
		qw422016.N().S(`
            Disabled
            `)
//line views/detailBlocks.qtpl:34
	}
//line views/detailBlocks.qtpl:34
	qw422016.N().S(`
            </span>
        </div>
        <div class="flex flex-col">
            <small class="text-xs font-semibold text-slate-500">Created at</small>
            <span>`)
//line views/detailBlocks.qtpl:39
	qw422016.E().S(device.CreatedAt.Format("Mon, 02 Jan 2006"))
//line views/detailBlocks.qtpl:39
	qw422016.N().S(`</span>
        </div>
        <div class="flex flex-col col-span-full">
            <small class="text-xs font-semibold text-slate-500">Description</small>
            <span>`)
//line views/detailBlocks.qtpl:43
	qw422016.E().S(device.Description)
//line views/detailBlocks.qtpl:43
	qw422016.N().S(`</span>
        </div>
        <div class="flex flex-col col-span-full">
            <small class="text-xs font-semibold text-slate-500">Location (Latitude, Longitude, Altitude)</small>
            <div class="grid grid-cols-3 items-center">
                `)
//line views/detailBlocks.qtpl:48
	if device.Latitude != nil && device.Longitude != nil {
//line views/detailBlocks.qtpl:48
		qw422016.N().S(`
                <span>`)
//line views/detailBlocks.qtpl:49
		qw422016.N().FPrec(float64(device.GetLatitude()), 3)
//line views/detailBlocks.qtpl:49
		qw422016.N().S(`</span>
                <span>`)
//line views/detailBlocks.qtpl:50
		qw422016.N().FPrec(float64(device.GetLongitude()), 3)
//line views/detailBlocks.qtpl:50
		qw422016.N().S(`</span>
                `)
//line views/detailBlocks.qtpl:51
	} else {
//line views/detailBlocks.qtpl:51
		qw422016.N().S(`
                <span>No latitude</span>
                <span>No longitude</span>
                `)
//line views/detailBlocks.qtpl:54
	}
//line views/detailBlocks.qtpl:54
	qw422016.N().S(`
                `)
//line views/detailBlocks.qtpl:55
	if device.Altitude != nil {
//line views/detailBlocks.qtpl:55
		qw422016.N().S(`
                <span>`)
//line views/detailBlocks.qtpl:56
		qw422016.N().FPrec(float64(device.GetAltitude()), 3)
//line views/detailBlocks.qtpl:56
		qw422016.N().S(`</span>
                `)
//line views/detailBlocks.qtpl:57
	}
//line views/detailBlocks.qtpl:57
	qw422016.N().S(`
                <span class="col-span-full">`)
//line views/detailBlocks.qtpl:58
	qw422016.E().S(device.GetLocationDescription())
//line views/detailBlocks.qtpl:58
	qw422016.N().S(`</span>
            </div>
        </div>
        <div class="flex flex-col col-span-full">
            <small class="text-xs font-semibold text-slate-500">Properties</small>
            `)
//line views/detailBlocks.qtpl:64
	deviceProps, _ := json.Marshal(device.Properties)

//line views/detailBlocks.qtpl:65
	qw422016.N().S(`
            <span>`)
//line views/detailBlocks.qtpl:66
	qw422016.E().S(string(deviceProps))
//line views/detailBlocks.qtpl:66
	qw422016.N().S(`</span>
        </div>
    </div>
`)
//line views/detailBlocks.qtpl:69
}

//line views/detailBlocks.qtpl:69
func WriteDeviceDetailBlock(qq422016 qtio422016.Writer, device api.Device) {
//line views/detailBlocks.qtpl:69
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/detailBlocks.qtpl:69
	StreamDeviceDetailBlock(qw422016, device)
//line views/detailBlocks.qtpl:69
	qt422016.ReleaseWriter(qw422016)
//line views/detailBlocks.qtpl:69
}

//line views/detailBlocks.qtpl:69
func DeviceDetailBlock(device api.Device) string {
//line views/detailBlocks.qtpl:69
	qb422016 := qt422016.AcquireByteBuffer()
//line views/detailBlocks.qtpl:69
	WriteDeviceDetailBlock(qb422016, device)
//line views/detailBlocks.qtpl:69
	qs422016 := string(qb422016.B)
//line views/detailBlocks.qtpl:69
	qt422016.ReleaseByteBuffer(qb422016)
//line views/detailBlocks.qtpl:69
	return qs422016
//line views/detailBlocks.qtpl:69
}

//line views/detailBlocks.qtpl:71
func StreamSensorDetailBlock(qw422016 *qt422016.Writer, sensor api.Sensor) {
//line views/detailBlocks.qtpl:71
	qw422016.N().S(`
    <div class="grid grid-cols-3 gap-x-8 gap-y-3 [&>*]:min-h-[2rem] text-sm">
        <div class="flex flex-col">
            <small class="text-xs font-semibold text-slate-500">Sensor ID</small>
            <span>`)
//line views/detailBlocks.qtpl:75
	qw422016.N().DL(sensor.Id)
//line views/detailBlocks.qtpl:75
	qw422016.N().S(`</span>
        </div>
        <div class="flex flex-col">
            <small class="text-xs font-semibold text-slate-500">Sensor Code</small>
            <span>`)
//line views/detailBlocks.qtpl:79
	qw422016.E().S(sensor.Code)
//line views/detailBlocks.qtpl:79
	qw422016.N().S(`</span>
        </div>
        <div class="flex flex-col">
            <small class="text-xs font-semibold text-slate-500">Sensor Brand</small>
            <span>`)
//line views/detailBlocks.qtpl:83
	qw422016.E().S(sensor.Brand)
//line views/detailBlocks.qtpl:83
	qw422016.N().S(`</span>
        </div>
        <div class="flex flex-col">
            <small class="text-xs font-semibold text-slate-500">Archive Time</small>
            <span>
            `)
//line views/detailBlocks.qtpl:88
	if sensor.ArchiveTime != nil {
//line views/detailBlocks.qtpl:88
		qw422016.N().S(`
                `)
//line views/detailBlocks.qtpl:89
		qw422016.N().D(int(sensor.GetArchiveTime()))
//line views/detailBlocks.qtpl:89
		qw422016.N().S(` days
            `)
//line views/detailBlocks.qtpl:90
	} else {
//line views/detailBlocks.qtpl:90
		qw422016.N().S(`
                Not set
            `)
//line views/detailBlocks.qtpl:92
	}
//line views/detailBlocks.qtpl:92
	qw422016.N().S(`
            </span>
        </div>
        <div class="flex flex-col">
            <small class="text-xs font-semibold text-slate-500">Parent Device ID</small>
            <span>`)
//line views/detailBlocks.qtpl:97
	qw422016.N().DL(sensor.DeviceId)
//line views/detailBlocks.qtpl:97
	qw422016.N().S(`</span>
        </div>
        <div class="flex flex-col">
            <small class="text-xs font-semibold text-slate-500">External ID</small>
            <span>`)
//line views/detailBlocks.qtpl:101
	qw422016.E().S(sensor.ExternalId)
//line views/detailBlocks.qtpl:101
	qw422016.N().S(`</span>
        </div>
        <div class="flex flex-col col-span-full">
            <small class="text-xs font-semibold text-slate-500">Properties</small>
            `)
//line views/detailBlocks.qtpl:106
	sensorProps, _ := json.Marshal(sensor.Properties)

//line views/detailBlocks.qtpl:107
	qw422016.N().S(`
            <span>`)
//line views/detailBlocks.qtpl:108
	qw422016.E().S(string(sensorProps))
//line views/detailBlocks.qtpl:108
	qw422016.N().S(`</span>
        </div>
    </div>
`)
//line views/detailBlocks.qtpl:111
}

//line views/detailBlocks.qtpl:111
func WriteSensorDetailBlock(qq422016 qtio422016.Writer, sensor api.Sensor) {
//line views/detailBlocks.qtpl:111
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/detailBlocks.qtpl:111
	StreamSensorDetailBlock(qw422016, sensor)
//line views/detailBlocks.qtpl:111
	qt422016.ReleaseWriter(qw422016)
//line views/detailBlocks.qtpl:111
}

//line views/detailBlocks.qtpl:111
func SensorDetailBlock(sensor api.Sensor) string {
//line views/detailBlocks.qtpl:111
	qb422016 := qt422016.AcquireByteBuffer()
//line views/detailBlocks.qtpl:111
	WriteSensorDetailBlock(qb422016, sensor)
//line views/detailBlocks.qtpl:111
	qs422016 := string(qb422016.B)
//line views/detailBlocks.qtpl:111
	qt422016.ReleaseByteBuffer(qb422016)
//line views/detailBlocks.qtpl:111
	return qs422016
//line views/detailBlocks.qtpl:111
}

//line views/detailBlocks.qtpl:113
func streamrenderDeviceMap(qw422016 *qt422016.Writer, device api.Device) {
//line views/detailBlocks.qtpl:113
	qw422016.N().S(`
    `)
//line views/detailBlocks.qtpl:114
	if device.Latitude != nil && device.Longitude != nil {
//line views/detailBlocks.qtpl:114
		qw422016.N().S(`
        <div
            class="w-full h-96" 
            id="device-map"
            hx-ext="leaflet" 
            data-latitude="`)
//line views/detailBlocks.qtpl:119
		qw422016.N().F(*device.Latitude)
//line views/detailBlocks.qtpl:119
		qw422016.N().S(`"
            data-longitude="`)
//line views/detailBlocks.qtpl:120
		qw422016.N().F(*device.Longitude)
//line views/detailBlocks.qtpl:120
		qw422016.N().S(`"
            data-zoom="11"
        >
            <map-marker
                latitude="`)
//line views/detailBlocks.qtpl:124
		qw422016.N().F(*device.Latitude)
//line views/detailBlocks.qtpl:124
		qw422016.N().S(`"
                longitude="`)
//line views/detailBlocks.qtpl:125
		qw422016.N().F(*device.Longitude)
//line views/detailBlocks.qtpl:125
		qw422016.N().S(`"
                label="`)
//line views/detailBlocks.qtpl:126
		qw422016.E().S(device.Code)
//line views/detailBlocks.qtpl:126
		qw422016.N().S(`"
            ></map-marker>
        </div>
    `)
//line views/detailBlocks.qtpl:129
	} else {
//line views/detailBlocks.qtpl:129
		qw422016.N().S(`
        <span> Device has no location set </span>
    `)
//line views/detailBlocks.qtpl:131
	}
//line views/detailBlocks.qtpl:131
	qw422016.N().S(`
`)
//line views/detailBlocks.qtpl:132
}

//line views/detailBlocks.qtpl:132
func writerenderDeviceMap(qq422016 qtio422016.Writer, device api.Device) {
//line views/detailBlocks.qtpl:132
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/detailBlocks.qtpl:132
	streamrenderDeviceMap(qw422016, device)
//line views/detailBlocks.qtpl:132
	qt422016.ReleaseWriter(qw422016)
//line views/detailBlocks.qtpl:132
}

//line views/detailBlocks.qtpl:132
func renderDeviceMap(device api.Device) string {
//line views/detailBlocks.qtpl:132
	qb422016 := qt422016.AcquireByteBuffer()
//line views/detailBlocks.qtpl:132
	writerenderDeviceMap(qb422016, device)
//line views/detailBlocks.qtpl:132
	qs422016 := string(qb422016.B)
//line views/detailBlocks.qtpl:132
	qt422016.ReleaseByteBuffer(qb422016)
//line views/detailBlocks.qtpl:132
	return qs422016
//line views/detailBlocks.qtpl:132
}
