// Code generated by qtc from "deviceDetailPage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line services/dashboard/views/deviceDetailPage.qtpl:1
package views

//line services/dashboard/views/deviceDetailPage.qtpl:1
import "sensorbucket.nl/sensorbucket/services/core/devices"

//line services/dashboard/views/deviceDetailPage.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line services/dashboard/views/deviceDetailPage.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line services/dashboard/views/deviceDetailPage.qtpl:3
func (p *DeviceDetailPage) StreamBody(qw422016 *qt422016.Writer) {
//line services/dashboard/views/deviceDetailPage.qtpl:3
	qw422016.N().S(`
    <div class="mx-auto w-full grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div class="bg-white border rounded-md">
            `)
//line services/dashboard/views/deviceDetailPage.qtpl:6
	streamrenderDeviceMap(qw422016, p.Device)
//line services/dashboard/views/deviceDetailPage.qtpl:6
	qw422016.N().S(`
        </div>
        <div class="bg-white border rounded-md">
            <header class="border-b py-2 px-4 text-sm text-slate-700">
                Device details
            </header>
            <div class="p-4">
                `)
//line services/dashboard/views/deviceDetailPage.qtpl:13
	StreamDeviceDetailBlock(qw422016, p.Device)
//line services/dashboard/views/deviceDetailPage.qtpl:13
	qw422016.N().S(`
            </div>
        </div>
        <div class="bg-white border rounded-md max-h-96 overflow-y-auto col-span-2">
            <table class="w-full text-sm border-separate border-spacing-0">
                <thead class="text-left text-slate-500 sticky top-0 bg-white">
                    <tr class="h-10">
                        <th class="font-normal border-b align-middle px-4">
                            Sensor ID
                        </th>
                        <th class="font-normal border-b align-middle px-4">
                            Code
                        </th>
                        <th class="font-normal border-b align-middle px-4">
                            Brand
                        </th>
                        <th class="font-normal border-b align-middle px-4">
                            Description
                        </th>
                    </tr>
                </thead>
                <tbody>
                    `)
//line services/dashboard/views/deviceDetailPage.qtpl:35
	for _, sensor := range p.Device.Sensors {
//line services/dashboard/views/deviceDetailPage.qtpl:35
		qw422016.N().S(`
                    <tr class="hover:bg-slate-50 group">
                        <td class="px-4 h-10 border-b">`)
//line services/dashboard/views/deviceDetailPage.qtpl:37
		qw422016.N().DL(sensor.ID)
//line services/dashboard/views/deviceDetailPage.qtpl:37
		qw422016.N().S(`</td>
                        <td class="border-b"><a
                            class="flex items-center px-4 h-10 text-primary-700 group-hover:underline"
                            href="/overview/devices/`)
//line services/dashboard/views/deviceDetailPage.qtpl:40
		qw422016.N().DL(p.Device.ID)
//line services/dashboard/views/deviceDetailPage.qtpl:40
		qw422016.N().S(`/sensors/`)
//line services/dashboard/views/deviceDetailPage.qtpl:40
		qw422016.E().S(sensor.Code)
//line services/dashboard/views/deviceDetailPage.qtpl:40
		qw422016.N().S(`"
                            hx-target="main"
                        >`)
//line services/dashboard/views/deviceDetailPage.qtpl:42
		qw422016.E().S(sensor.Code)
//line services/dashboard/views/deviceDetailPage.qtpl:42
		qw422016.N().S(`</a></td>
                        <td class="px-4 h-10 border-b">`)
//line services/dashboard/views/deviceDetailPage.qtpl:43
		qw422016.E().S(sensor.Brand)
//line services/dashboard/views/deviceDetailPage.qtpl:43
		qw422016.N().S(`</td>
                        <td class="px-4 h-10 border-b">`)
//line services/dashboard/views/deviceDetailPage.qtpl:44
		qw422016.E().S(sensor.Description)
//line services/dashboard/views/deviceDetailPage.qtpl:44
		qw422016.N().S(`</td>
                    </tr>
                    `)
//line services/dashboard/views/deviceDetailPage.qtpl:46
	}
//line services/dashboard/views/deviceDetailPage.qtpl:46
	qw422016.N().S(`
                </tbody>
            </table>
        </div>
    </div>
`)
//line services/dashboard/views/deviceDetailPage.qtpl:51
}

//line services/dashboard/views/deviceDetailPage.qtpl:51
func (p *DeviceDetailPage) WriteBody(qq422016 qtio422016.Writer) {
//line services/dashboard/views/deviceDetailPage.qtpl:51
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services/dashboard/views/deviceDetailPage.qtpl:51
	p.StreamBody(qw422016)
//line services/dashboard/views/deviceDetailPage.qtpl:51
	qt422016.ReleaseWriter(qw422016)
//line services/dashboard/views/deviceDetailPage.qtpl:51
}

//line services/dashboard/views/deviceDetailPage.qtpl:51
func (p *DeviceDetailPage) Body() string {
//line services/dashboard/views/deviceDetailPage.qtpl:51
	qb422016 := qt422016.AcquireByteBuffer()
//line services/dashboard/views/deviceDetailPage.qtpl:51
	p.WriteBody(qb422016)
//line services/dashboard/views/deviceDetailPage.qtpl:51
	qs422016 := string(qb422016.B)
//line services/dashboard/views/deviceDetailPage.qtpl:51
	qt422016.ReleaseByteBuffer(qb422016)
//line services/dashboard/views/deviceDetailPage.qtpl:51
	return qs422016
//line services/dashboard/views/deviceDetailPage.qtpl:51
}

//line services/dashboard/views/deviceDetailPage.qtpl:54
type DeviceDetailPage struct {
	BasePage
	Device devices.Device
}
