// Code generated by qtc from "overview.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line services/dashboard/views/overview.qtpl:1
package views

//line services/dashboard/views/overview.qtpl:1
import "sensorbucket.nl/sensorbucket/services/core/devices"

//line services/dashboard/views/overview.qtpl:2
import "sensorbucket.nl/sensorbucket/services/core/measurements"

//line services/dashboard/views/overview.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line services/dashboard/views/overview.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line services/dashboard/views/overview.qtpl:4
func (p *OverviewPage) StreamBody(qw422016 *qt422016.Writer) {
//line services/dashboard/views/overview.qtpl:4
	qw422016.N().S(`
<div class="w-[1024px] bg-white border mx-auto">
    <h1 class="px-2">Device tree</h1>
    <hr/>
    <ul class="p-2 text-sm">
        `)
//line services/dashboard/views/overview.qtpl:9
	for _, device := range p.Devices {
//line services/dashboard/views/overview.qtpl:9
		qw422016.N().S(`
        `)
//line services/dashboard/views/overview.qtpl:10
		streamdeviceRow(qw422016, device)
//line services/dashboard/views/overview.qtpl:10
		qw422016.N().S(`
        `)
//line services/dashboard/views/overview.qtpl:11
	}
//line services/dashboard/views/overview.qtpl:11
	qw422016.N().S(`
    </ul>
</div>
`)
//line services/dashboard/views/overview.qtpl:14
}

//line services/dashboard/views/overview.qtpl:14
func (p *OverviewPage) WriteBody(qq422016 qtio422016.Writer) {
//line services/dashboard/views/overview.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services/dashboard/views/overview.qtpl:14
	p.StreamBody(qw422016)
//line services/dashboard/views/overview.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line services/dashboard/views/overview.qtpl:14
}

//line services/dashboard/views/overview.qtpl:14
func (p *OverviewPage) Body() string {
//line services/dashboard/views/overview.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line services/dashboard/views/overview.qtpl:14
	p.WriteBody(qb422016)
//line services/dashboard/views/overview.qtpl:14
	qs422016 := string(qb422016.B)
//line services/dashboard/views/overview.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line services/dashboard/views/overview.qtpl:14
	return qs422016
//line services/dashboard/views/overview.qtpl:14
}

//line services/dashboard/views/overview.qtpl:16
func streamdeviceRow(qw422016 *qt422016.Writer, device devices.Device) {
//line services/dashboard/views/overview.qtpl:16
	qw422016.N().S(`
    <li>
        <div 
            _="on click toggle .hidden on next <ul/>"
            class="flex justify-between p-2 my-1 border">
            <h3>`)
//line services/dashboard/views/overview.qtpl:21
	qw422016.E().S(device.Code)
//line services/dashboard/views/overview.qtpl:21
	qw422016.N().S(`</h3>
            <span class="text-sm text-slate-400">`)
//line services/dashboard/views/overview.qtpl:22
	qw422016.E().S(device.Description)
//line services/dashboard/views/overview.qtpl:22
	qw422016.N().S(`</span>
            <span class="text-sm text-slate-400">`)
//line services/dashboard/views/overview.qtpl:23
	qw422016.E().S(device.LocationDescription)
//line services/dashboard/views/overview.qtpl:23
	qw422016.N().S(`</span>
        </div>
        <ul class="pl-6 border-l">
            `)
//line services/dashboard/views/overview.qtpl:26
	for _, sensor := range device.Sensors {
//line services/dashboard/views/overview.qtpl:26
		qw422016.N().S(`
                `)
//line services/dashboard/views/overview.qtpl:27
		StreamSensorRow(qw422016, sensor, nil, false)
//line services/dashboard/views/overview.qtpl:27
		qw422016.N().S(`
            `)
//line services/dashboard/views/overview.qtpl:28
	}
//line services/dashboard/views/overview.qtpl:28
	qw422016.N().S(`
        </ul>
    </li>
`)
//line services/dashboard/views/overview.qtpl:31
}

//line services/dashboard/views/overview.qtpl:31
func writedeviceRow(qq422016 qtio422016.Writer, device devices.Device) {
//line services/dashboard/views/overview.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services/dashboard/views/overview.qtpl:31
	streamdeviceRow(qw422016, device)
//line services/dashboard/views/overview.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line services/dashboard/views/overview.qtpl:31
}

//line services/dashboard/views/overview.qtpl:31
func deviceRow(device devices.Device) string {
//line services/dashboard/views/overview.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line services/dashboard/views/overview.qtpl:31
	writedeviceRow(qb422016, device)
//line services/dashboard/views/overview.qtpl:31
	qs422016 := string(qb422016.B)
//line services/dashboard/views/overview.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line services/dashboard/views/overview.qtpl:31
	return qs422016
//line services/dashboard/views/overview.qtpl:31
}

//line services/dashboard/views/overview.qtpl:33
func StreamSensorRow(qw422016 *qt422016.Writer, sensor devices.Sensor, datastreams []measurements.Datastream, isLoaded bool) {
//line services/dashboard/views/overview.qtpl:33
	qw422016.N().S(`
    <li 
        `)
//line services/dashboard/views/overview.qtpl:35
	if !isLoaded {
//line services/dashboard/views/overview.qtpl:35
		qw422016.N().S(`
            hx-get="/overview/sensors/`)
//line services/dashboard/views/overview.qtpl:36
		qw422016.N().DL(sensor.ID)
//line services/dashboard/views/overview.qtpl:36
		qw422016.N().S(`"
            hx-swap="outerHTML"
        `)
//line services/dashboard/views/overview.qtpl:38
	}
//line services/dashboard/views/overview.qtpl:38
	qw422016.N().S(`
    >
        <div
            `)
//line services/dashboard/views/overview.qtpl:41
	if isLoaded {
//line services/dashboard/views/overview.qtpl:41
		qw422016.N().S(`
                _="on click toggle .hidden on next <ul/>"
            `)
//line services/dashboard/views/overview.qtpl:43
	}
//line services/dashboard/views/overview.qtpl:43
	qw422016.N().S(`
            class="flex gap-4 p-2 border my-1">
            <h3>`)
//line services/dashboard/views/overview.qtpl:45
	qw422016.E().S(sensor.Code)
//line services/dashboard/views/overview.qtpl:45
	qw422016.N().S(`</h3>
            <span class="text-sm text-slate-400">`)
//line services/dashboard/views/overview.qtpl:46
	qw422016.E().S(sensor.Description)
//line services/dashboard/views/overview.qtpl:46
	qw422016.N().S(`</span>
        </div>
        <ul class="pl-6 border-l">
            `)
//line services/dashboard/views/overview.qtpl:49
	for _, ds := range datastreams {
//line services/dashboard/views/overview.qtpl:49
		qw422016.N().S(`
                `)
//line services/dashboard/views/overview.qtpl:50
		streamdatastreamRow(qw422016, ds)
//line services/dashboard/views/overview.qtpl:50
		qw422016.N().S(`
            `)
//line services/dashboard/views/overview.qtpl:51
	}
//line services/dashboard/views/overview.qtpl:51
	qw422016.N().S(`
        </ul>
    </li>
`)
//line services/dashboard/views/overview.qtpl:54
}

//line services/dashboard/views/overview.qtpl:54
func WriteSensorRow(qq422016 qtio422016.Writer, sensor devices.Sensor, datastreams []measurements.Datastream, isLoaded bool) {
//line services/dashboard/views/overview.qtpl:54
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services/dashboard/views/overview.qtpl:54
	StreamSensorRow(qw422016, sensor, datastreams, isLoaded)
//line services/dashboard/views/overview.qtpl:54
	qt422016.ReleaseWriter(qw422016)
//line services/dashboard/views/overview.qtpl:54
}

//line services/dashboard/views/overview.qtpl:54
func SensorRow(sensor devices.Sensor, datastreams []measurements.Datastream, isLoaded bool) string {
//line services/dashboard/views/overview.qtpl:54
	qb422016 := qt422016.AcquireByteBuffer()
//line services/dashboard/views/overview.qtpl:54
	WriteSensorRow(qb422016, sensor, datastreams, isLoaded)
//line services/dashboard/views/overview.qtpl:54
	qs422016 := string(qb422016.B)
//line services/dashboard/views/overview.qtpl:54
	qt422016.ReleaseByteBuffer(qb422016)
//line services/dashboard/views/overview.qtpl:54
	return qs422016
//line services/dashboard/views/overview.qtpl:54
}

//line services/dashboard/views/overview.qtpl:56
func streamdatastreamRow(qw422016 *qt422016.Writer, ds measurements.Datastream) {
//line services/dashboard/views/overview.qtpl:56
	qw422016.N().S(`
    <li>
        <a href="/overview/datastreams/`)
//line services/dashboard/views/overview.qtpl:58
	qw422016.E().S(ds.ID.String())
//line services/dashboard/views/overview.qtpl:58
	qw422016.N().S(`" class="block p-2 border my-1">`)
//line services/dashboard/views/overview.qtpl:58
	qw422016.E().S(ds.ObservedProperty)
//line services/dashboard/views/overview.qtpl:58
	qw422016.N().S(`</a>
    </li>
`)
//line services/dashboard/views/overview.qtpl:60
}

//line services/dashboard/views/overview.qtpl:60
func writedatastreamRow(qq422016 qtio422016.Writer, ds measurements.Datastream) {
//line services/dashboard/views/overview.qtpl:60
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services/dashboard/views/overview.qtpl:60
	streamdatastreamRow(qw422016, ds)
//line services/dashboard/views/overview.qtpl:60
	qt422016.ReleaseWriter(qw422016)
//line services/dashboard/views/overview.qtpl:60
}

//line services/dashboard/views/overview.qtpl:60
func datastreamRow(ds measurements.Datastream) string {
//line services/dashboard/views/overview.qtpl:60
	qb422016 := qt422016.AcquireByteBuffer()
//line services/dashboard/views/overview.qtpl:60
	writedatastreamRow(qb422016, ds)
//line services/dashboard/views/overview.qtpl:60
	qs422016 := string(qb422016.B)
//line services/dashboard/views/overview.qtpl:60
	qt422016.ReleaseByteBuffer(qb422016)
//line services/dashboard/views/overview.qtpl:60
	return qs422016
//line services/dashboard/views/overview.qtpl:60
}

//line services/dashboard/views/overview.qtpl:64
type OverviewPage struct {
	BasePage
	Devices []devices.Device
}
