// Code generated by qtc from "sensorDetailPage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line services/dashboard/views/sensorDetailPage.qtpl:1
package views

//line services/dashboard/views/sensorDetailPage.qtpl:1
import "sensorbucket.nl/sensorbucket/services/core/devices"

//line services/dashboard/views/sensorDetailPage.qtpl:2
import "sensorbucket.nl/sensorbucket/services/core/measurements"

//line services/dashboard/views/sensorDetailPage.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line services/dashboard/views/sensorDetailPage.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line services/dashboard/views/sensorDetailPage.qtpl:4
func (p *SensorDetailPage) StreamBody(qw422016 *qt422016.Writer) {
//line services/dashboard/views/sensorDetailPage.qtpl:4
	qw422016.N().S(`
    <div class="mx-auto grid grid-cols-3 gap-6">
        <div class="bg-white border rounded-md">
            <div class="w-full h-96" hx-ext="leaflet"></div>
        </div>
        <div class="bg-white border rounded-md">
            <div class="w-full h-24"></div>
        </div>
        <div class="bg-white border rounded-md">
            <div class="w-full h-24"></div>
        </div>
        <div class="bg-white border rounded-md max-h-96 overflow-y-auto col-span-3">
            <table class="w-full text-sm border-separate border-spacing-0">
                <thead class="text-left text-slate-500 sticky top-0 bg-white">
                    <tr class="h-10">
                        <th class="font-normal border-b align-middle px-4">
                            Datastream ID
                        </th>
                        <th class="font-normal border-b align-middle px-4">
                            Observed property
                        </th>
                        <th class="font-normal border-b align-middle px-4">
                            Unit of measurement
                        </th>
                        <th class="font-normal border-b align-middle px-4">
                            Description
                        </th>
                    </tr>
                </thead>
                <tbody>
                    `)
//line services/dashboard/views/sensorDetailPage.qtpl:34
	for _, datastream := range p.Datastreams {
//line services/dashboard/views/sensorDetailPage.qtpl:34
		qw422016.N().S(`
                    <tr class="hover:bg-slate-50 group">
                        <td class="border-b"><a
                            class="flex items-center px-4 h-10 text-primary-700 group-hover:underline"
                            href="/overview/datastreams/`)
//line services/dashboard/views/sensorDetailPage.qtpl:38
		qw422016.E().S(datastream.ID.String())
//line services/dashboard/views/sensorDetailPage.qtpl:38
		qw422016.N().S(`"
                            hx-target="main"
                        >`)
//line services/dashboard/views/sensorDetailPage.qtpl:40
		qw422016.E().S(datastream.ID.String())
//line services/dashboard/views/sensorDetailPage.qtpl:40
		qw422016.N().S(`</a></td>
                        <td class="px-4 h-10 border-b">`)
//line services/dashboard/views/sensorDetailPage.qtpl:41
		qw422016.E().S(datastream.ObservedProperty)
//line services/dashboard/views/sensorDetailPage.qtpl:41
		qw422016.N().S(`</td>
                        <td class="px-4 h-10 border-b">`)
//line services/dashboard/views/sensorDetailPage.qtpl:42
		qw422016.E().S(datastream.UnitOfMeasurement)
//line services/dashboard/views/sensorDetailPage.qtpl:42
		qw422016.N().S(`</td>
                        <td class="px-4 h-10 border-b">`)
//line services/dashboard/views/sensorDetailPage.qtpl:43
		qw422016.E().S(datastream.Description)
//line services/dashboard/views/sensorDetailPage.qtpl:43
		qw422016.N().S(`</td>
                    </tr>
                    `)
//line services/dashboard/views/sensorDetailPage.qtpl:45
	}
//line services/dashboard/views/sensorDetailPage.qtpl:45
	qw422016.N().S(`
                </tbody>
            </table>
        </div>
    </div>
`)
//line services/dashboard/views/sensorDetailPage.qtpl:50
}

//line services/dashboard/views/sensorDetailPage.qtpl:50
func (p *SensorDetailPage) WriteBody(qq422016 qtio422016.Writer) {
//line services/dashboard/views/sensorDetailPage.qtpl:50
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services/dashboard/views/sensorDetailPage.qtpl:50
	p.StreamBody(qw422016)
//line services/dashboard/views/sensorDetailPage.qtpl:50
	qt422016.ReleaseWriter(qw422016)
//line services/dashboard/views/sensorDetailPage.qtpl:50
}

//line services/dashboard/views/sensorDetailPage.qtpl:50
func (p *SensorDetailPage) Body() string {
//line services/dashboard/views/sensorDetailPage.qtpl:50
	qb422016 := qt422016.AcquireByteBuffer()
//line services/dashboard/views/sensorDetailPage.qtpl:50
	p.WriteBody(qb422016)
//line services/dashboard/views/sensorDetailPage.qtpl:50
	qs422016 := string(qb422016.B)
//line services/dashboard/views/sensorDetailPage.qtpl:50
	qt422016.ReleaseByteBuffer(qb422016)
//line services/dashboard/views/sensorDetailPage.qtpl:50
	return qs422016
//line services/dashboard/views/sensorDetailPage.qtpl:50
}

//line services/dashboard/views/sensorDetailPage.qtpl:53
type SensorDetailPage struct {
	BasePage
	Device      devices.Device
	Sensor      devices.Sensor
	Datastreams []measurements.Datastream
}
