// Code generated by qtc from "workersPage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line services/dashboard/views/workersPage.qtpl:1
package views

//line services/dashboard/views/workersPage.qtpl:1
import "sensorbucket.nl/sensorbucket/pkg/api"

//line services/dashboard/views/workersPage.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line services/dashboard/views/workersPage.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line services/dashboard/views/workersPage.qtpl:3
func (p *WorkerListPage) StreamBody(qw422016 *qt422016.Writer) {
//line services/dashboard/views/workersPage.qtpl:3
	qw422016.N().S(`
    <div 
        class="w-full xl:w-2/3 mx-auto bg-white border rounded-md"
    >
        <header class="border-b py-2 px-4 text-sm text-slate-700">
            SensorBucket Worker List
        </header>
        <div>
            `)
//line services/dashboard/views/workersPage.qtpl:11
	StreamRenderWorkerTable(qw422016, p.Workers)
//line services/dashboard/views/workersPage.qtpl:11
	qw422016.N().S(`
        </div>
    </div>
`)
//line services/dashboard/views/workersPage.qtpl:14
}

//line services/dashboard/views/workersPage.qtpl:14
func (p *WorkerListPage) WriteBody(qq422016 qtio422016.Writer) {
//line services/dashboard/views/workersPage.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services/dashboard/views/workersPage.qtpl:14
	p.StreamBody(qw422016)
//line services/dashboard/views/workersPage.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line services/dashboard/views/workersPage.qtpl:14
}

//line services/dashboard/views/workersPage.qtpl:14
func (p *WorkerListPage) Body() string {
//line services/dashboard/views/workersPage.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line services/dashboard/views/workersPage.qtpl:14
	p.WriteBody(qb422016)
//line services/dashboard/views/workersPage.qtpl:14
	qs422016 := string(qb422016.B)
//line services/dashboard/views/workersPage.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line services/dashboard/views/workersPage.qtpl:14
	return qs422016
//line services/dashboard/views/workersPage.qtpl:14
}

//line services/dashboard/views/workersPage.qtpl:16
func StreamRenderWorkerTable(qw422016 *qt422016.Writer, workers []api.UserWorker) {
//line services/dashboard/views/workersPage.qtpl:16
	qw422016.N().S(`
    <table class="w-full text-sm border-separate border-spacing-0" id="device-table">
        <thead class="text-left text-slate-500 sticky top-0 bg-white">
            <tr class="h-10">
                <th class="font-normal border-b align-middle px-4">
                    Name
                </th>
                <th class="font-normal border-b align-middle px-4">
                    Major version
                </th>
                <th class="font-normal border-b align-middle px-4">
                    Revision
                </th>
                <th class="font-normal border-b align-middle px-4">
                    ID
                </th>
                <th class="font-normal border-b align-middle px-4">
                    Description
                </th>
                <th class="font-normal border-b align-middle px-4">
                    Language
                </th>
            </tr>
        </thead>
        <tbody>
            `)
//line services/dashboard/views/workersPage.qtpl:41
	StreamRenderWorkerTableRows(qw422016, workers, "")
//line services/dashboard/views/workersPage.qtpl:41
	qw422016.N().S(`
        </tbody>
    </table>
`)
//line services/dashboard/views/workersPage.qtpl:44
}

//line services/dashboard/views/workersPage.qtpl:44
func WriteRenderWorkerTable(qq422016 qtio422016.Writer, workers []api.UserWorker) {
//line services/dashboard/views/workersPage.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services/dashboard/views/workersPage.qtpl:44
	StreamRenderWorkerTable(qw422016, workers)
//line services/dashboard/views/workersPage.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line services/dashboard/views/workersPage.qtpl:44
}

//line services/dashboard/views/workersPage.qtpl:44
func RenderWorkerTable(workers []api.UserWorker) string {
//line services/dashboard/views/workersPage.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
//line services/dashboard/views/workersPage.qtpl:44
	WriteRenderWorkerTable(qb422016, workers)
//line services/dashboard/views/workersPage.qtpl:44
	qs422016 := string(qb422016.B)
//line services/dashboard/views/workersPage.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
//line services/dashboard/views/workersPage.qtpl:44
	return qs422016
//line services/dashboard/views/workersPage.qtpl:44
}

//line services/dashboard/views/workersPage.qtpl:46
func StreamRenderWorkerTableRows(qw422016 *qt422016.Writer, workers []api.UserWorker, nextPage string) {
//line services/dashboard/views/workersPage.qtpl:46
	qw422016.N().S(`
    `)
//line services/dashboard/views/workersPage.qtpl:47
	for ix, worker := range workers {
//line services/dashboard/views/workersPage.qtpl:47
		qw422016.N().S(`
    <tr
        class="hover:bg-slate-50 group"
        `)
//line services/dashboard/views/workersPage.qtpl:50
		if nextPage != "" && ix == len(workers)-1 {
//line services/dashboard/views/workersPage.qtpl:50
			qw422016.N().S(`
        hx-trigger="revealed"
        hx-target="this"
        hx-swap="afterend"
        hx-get="`)
//line services/dashboard/views/workersPage.qtpl:54
			qw422016.E().S(nextPage)
//line services/dashboard/views/workersPage.qtpl:54
			qw422016.N().S(`"
        `)
//line services/dashboard/views/workersPage.qtpl:55
		}
//line services/dashboard/views/workersPage.qtpl:55
		qw422016.N().S(`
    >
        <td class="border-b"><a
            class="flex items-center px-4 h-10 text-primary-700 group-hover:underline"
            href="/workers/`)
//line services/dashboard/views/workersPage.qtpl:59
		qw422016.E().S(worker.Id)
//line services/dashboard/views/workersPage.qtpl:59
		qw422016.N().S(`"
            hx-target="main"
        >`)
//line services/dashboard/views/workersPage.qtpl:61
		qw422016.E().S(worker.Name)
//line services/dashboard/views/workersPage.qtpl:61
		qw422016.N().S(`</a></td>
        <td class="px-4 h-10 border-b">`)
//line services/dashboard/views/workersPage.qtpl:62
		qw422016.N().D(int(worker.Major))
//line services/dashboard/views/workersPage.qtpl:62
		qw422016.N().S(`</td>
        <td class="px-4 h-10 border-b">`)
//line services/dashboard/views/workersPage.qtpl:63
		qw422016.N().D(int(worker.Revision))
//line services/dashboard/views/workersPage.qtpl:63
		qw422016.N().S(`</td>
        <td class="px-4 h-10 border-b">`)
//line services/dashboard/views/workersPage.qtpl:64
		qw422016.E().S(worker.Id)
//line services/dashboard/views/workersPage.qtpl:64
		qw422016.N().S(`</td>
        <td class="px-4 h-10 border-b">`)
//line services/dashboard/views/workersPage.qtpl:65
		qw422016.E().S(worker.Description)
//line services/dashboard/views/workersPage.qtpl:65
		qw422016.N().S(`</td>
        <td class="px-4 h-10 border-b">Python</td>
    </tr>
    `)
//line services/dashboard/views/workersPage.qtpl:68
	}
//line services/dashboard/views/workersPage.qtpl:68
	qw422016.N().S(`
`)
//line services/dashboard/views/workersPage.qtpl:69
}

//line services/dashboard/views/workersPage.qtpl:69
func WriteRenderWorkerTableRows(qq422016 qtio422016.Writer, workers []api.UserWorker, nextPage string) {
//line services/dashboard/views/workersPage.qtpl:69
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services/dashboard/views/workersPage.qtpl:69
	StreamRenderWorkerTableRows(qw422016, workers, nextPage)
//line services/dashboard/views/workersPage.qtpl:69
	qt422016.ReleaseWriter(qw422016)
//line services/dashboard/views/workersPage.qtpl:69
}

//line services/dashboard/views/workersPage.qtpl:69
func RenderWorkerTableRows(workers []api.UserWorker, nextPage string) string {
//line services/dashboard/views/workersPage.qtpl:69
	qb422016 := qt422016.AcquireByteBuffer()
//line services/dashboard/views/workersPage.qtpl:69
	WriteRenderWorkerTableRows(qb422016, workers, nextPage)
//line services/dashboard/views/workersPage.qtpl:69
	qs422016 := string(qb422016.B)
//line services/dashboard/views/workersPage.qtpl:69
	qt422016.ReleaseByteBuffer(qb422016)
//line services/dashboard/views/workersPage.qtpl:69
	return qs422016
//line services/dashboard/views/workersPage.qtpl:69
}

//line services/dashboard/views/workersPage.qtpl:72
type WorkerListPage struct {
	BasePage
	Workers []api.UserWorker
}
