version: '3'

services:
  assetmanager:
    command: mage serve assetmanager
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    volumes:
      - ..:/workspace:cached
    environment:
      AM_PIPELINE_ID: mfm-waterlevel
      AM_DEFINITION_PATH: /workspace/tools/seed/assetmanager/assetdefinitions.json
      AM_HTTP_ADDR: :3000
      AM_MONGO_DSN: mongodb://root:root@assetdb:27017

  zmqbridge:
    command: mage serve zmqbridge
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      WORKER_AMQP_HOST: amqp://mq:5672
      WORKER_AMQP_XCHG: pipeline.measurement.tx
      WORKER_AMQP_ROUTE_KEY: grondwater
      WORKER_ZMQ_BIND: "tcp://*:5555"
    ports:
      - 5555:5555
    volumes:
      - ..:/workspace:cached
      
  measurements:
    command: mage serve measurements
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3001:3001
    volumes:
      - ..:/workspace:cached
    environment:
      MS_HTTP_BASE: http://localhost:3001
      MS_HTTP_ADDR: :3001
      MS_DB_DSN: postgresql://user:sensorbucket@db:5432/sensorbucket?sslmode=disable
      MS_AMQP_URL: amqp://guest:guest@mq:5672/
      MS_AMQP_EXCHANGE: pipeline.measurement.tx
      MS_AMQP_QUEUE: measurement_service_q
      MS_LOCATIONS_URL: http://locations:3000

  locations:
    command: mage serve locations
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3002:3000
    volumes:
      - ..:/workspace:cached
    environment:
      LOCATION_SVC_HTTP_HOST: ":3000"
      LOCATION_SVC_WORKER_DB_DSN: postgresql://user:sensorbucket@db:5432/locations

  locations:
    command: mage serve locations
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3002:3002
    volumes:
      - ..:/workspace:cached
    environment:
      LOCATION_SVC_HTTP_HOST: :3002
      LOCATION_SVC_WORKER_DB_DSN: postgresql://user:sensorbucket@db:5432/locations?sslmode=disable

  assetdb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  db:
    image: timescale/timescaledb-postgis:latest-pg12
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: sensorbucket
      POSTGRES_DB: sensorbucket

  mq:
    image: rabbitmq:3.8-management
    ports:
      - 5672:5672
      - 15672:15672

  # docs:
  #   image: squidfunk/mkdocs-material
  #   ports:
  #     - '8000:8000'
  #   volumes:
  #     - ..:/docs

networks:
  default:
    name: sensorbucket_network
