name: Build and Deploy Pages

on:
  push:
    branches:
      - main
      - deploy-docs-github
    paths:
      - 'docs/**'
      - 'tools/openapi/**'
      - 'mkdocs.yml'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - uses: actions/setup-python@v4
      with:
        python-version: 3

    - uses: actions/cache@v3
      with:
        key: mkdocs-material-${{ github.ref }} 
        path: .cache
        restore-keys: |
          mkdocs-material-
    - run: pip install mkdocs-material mkdocs-glightbox
    - run: mkdocs build -d public

    - name: Bundle OpenAPI spec with Redoc
      uses: seeebiii/redoc-cli-github-action@v10
      with:
        args: 'bundle test/petstore.yml -o public/api'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

