// Code generated by qtc from "error.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line error.qtpl:1
package views

//line error.qtpl:1
import ory "github.com/ory/client-go"

//line error.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line error.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line error.qtpl:3
type ErrorPage struct {
	Flow *ory.FlowError
}

//line error.qtpl:7
func (p ErrorPage) StreamBody(qw422016 *qt422016.Writer) {
//line error.qtpl:7
	qw422016.N().S(`
    <h1>Error!</h1>
    <span style="color: red;">`)
//line error.qtpl:9
	qw422016.E().S(p.Flow.GetError()["reason"].(string))
//line error.qtpl:9
	qw422016.N().S(`</span>
`)
//line error.qtpl:10
}

//line error.qtpl:10
func (p ErrorPage) WriteBody(qq422016 qtio422016.Writer) {
//line error.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line error.qtpl:10
	p.StreamBody(qw422016)
//line error.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line error.qtpl:10
}

//line error.qtpl:10
func (p ErrorPage) Body() string {
//line error.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
//line error.qtpl:10
	p.WriteBody(qb422016)
//line error.qtpl:10
	qs422016 := string(qb422016.B)
//line error.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
//line error.qtpl:10
	return qs422016
//line error.qtpl:10
}
